# Scikit Learn (sklearn) - Simple Workflow

what we are going to cover:
0. End to End Scikit learn workflow
1. Getting data ready
2. Choose the right estimator/algorithm for our problems
3. Fit the model/algorithm and use it to make predictions on our data
4. Evaluating the model
5. Improve the model
6. Save and load the trained model
7. Putting all together

# End to End Scikit Learn Workflow

## 1) get the data ready

In [1]:
import pandas as pd
import numpy as np
heart_disease = pd.read_csv("../00.datasets/heart-diseases.csv")
heart_disease.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [2]:
# create X (features matrix) excluding the "target" column
X = heart_disease.drop("target", axis=1)

# create y (labels)
y = heart_disease["target"]

## 2) Choose the right model / algorithm and hyperparameters


In [3]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier()

# we will keep the default hyperparameters
clf.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'auto',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_impurity_split': None,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

## 3) Fit the model/algorithm and use it to predict data

In [4]:
# split train and test data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [5]:
#  acutal training for fitting the line
clf.fit(X_train, y_train);

In [6]:
# make the prediction
y_preds = clf.predict(X_test)

In [7]:
y_preds

array([0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0], dtype=int64)

In [8]:
y_test

193    0
108    1
211    0
100    1
105    1
      ..
88     1
19     1
95     1
11     1
271    0
Name: target, Length: 61, dtype: int64

## 4) Evaluating the model

In [9]:
# evaluate the model on training and test data
clf.score(X_train, y_train)

1.0

In [10]:
clf.score(X_test, y_test)

0.8524590163934426

In [11]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

#get the report of performance of predictions, comparing with expected results
print(classification_report(y_test, y_preds))

              precision    recall  f1-score   support

           0       0.83      0.86      0.85        29
           1       0.87      0.84      0.86        32

    accuracy                           0.85        61
   macro avg       0.85      0.85      0.85        61
weighted avg       0.85      0.85      0.85        61



In [12]:
confusion_matrix(y_test, y_preds)

array([[25,  4],
       [ 5, 27]], dtype=int64)

In [13]:
accuracy_score(y_test, y_preds)

0.8524590163934426

## 5) Improve the model (Hyperparameter Tuning)

In [14]:
# try different amout of n_estimators
np.random.seed(42)
for i in range(10, 100, 10):
    print(f"Trying model with {i} estimators...")
    model = RandomForestClassifier(n_estimators = i)
    model.fit(X_train, y_train)
    print(f"Model accuracy on test set: {model.score(X_test, y_test)}")
    print("")

Trying model with 10 estimators...
Model accuracy on test set: 0.8032786885245902

Trying model with 20 estimators...
Model accuracy on test set: 0.7868852459016393

Trying model with 30 estimators...
Model accuracy on test set: 0.8688524590163934

Trying model with 40 estimators...
Model accuracy on test set: 0.9016393442622951

Trying model with 50 estimators...
Model accuracy on test set: 0.8688524590163934

Trying model with 60 estimators...
Model accuracy on test set: 0.7868852459016393

Trying model with 70 estimators...
Model accuracy on test set: 0.8852459016393442

Trying model with 80 estimators...
Model accuracy on test set: 0.8524590163934426

Trying model with 90 estimators...
Model accuracy on test set: 0.8360655737704918



## 6) Save the model for later use and load it

In [15]:
#use pickel to save the model
import pickle

pickle.dump(clf, open("models/random_forest_model_1.pkl", "wb")) #write binary

In [16]:
X_test.tail()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
88    54    0   2       110   214    0        1      158      0      1.6   
19    69    0   3       140   239    0        1      151      0      1.8   
95    53    1   0       142   226    0        0      111      1      0.0   
11    48    0   2       130   275    0        1      139      0      0.2   
271   61    1   3       134   234    0        1      145      0      2.6   

     slope  ca  thal  
88       1   0     2  
19       2   2     2  
95       2   0     3  
11       2   0     2  
271      1   2     2

In [17]:
# load from saved model and make predictions on single example

loaded_model = pickle.load(open("models/random_forest_model_1.pkl", "rb")) #read binary
loaded_model.score(X_test, y_test)

0.8524590163934426

-------------

# Practice again

In [1]:
#standard imports
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# 1.Get the data ready

In [3]:
heart_disease = pd.read_csv("../00.datasets/heart-diseases.csv")
heart_disease.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [8]:
#create X (features)
X = heart_disease.drop("target", axis = 1)

#create y (label)
y = heart_disease["target"]

In [14]:
#split the data into training and test sets
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y)

#view the data shape
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((227, 13), (76, 13), (227,), (76,))

# 2.Choose Model / Estimator

In [16]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier()

# 3.Fit the Model to the data and use it to make a prediction

In [19]:
model.fit(X_train, y_train)

RandomForestClassifier()

In [20]:
#once the model has learned, we can make prediction
y_preds = model.predict(X_test)

In [21]:
# this will be same as y_test
y_preds

array([1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0,
       1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1,
       1, 1, 0, 1, 0, 1, 1, 0, 0, 0], dtype=int64)

# 4. Evaluate the model

In [22]:
# a trained model can be evaluated by calling score() function and passing it a collection of data

#on the training set
model.score(X_train, y_train)

1.0

In [23]:
#on the testing set (unseen)
model.score(X_test, y_test)

0.8552631578947368

# 5. Improve Models : Experiment to improve (hyperparameter tuning)

In [28]:
#one way to improve model prediction is hyperparameter tuning
np.random.seed(42)
for i in range(10, 100, 10):
    print(f"Trying model with {i} estimator...")
    model = RandomForestClassifier(n_estimators=i).fit(X_train, y_train)
    print(f"Model accuracy on test set: {model.score(X_test, y_test)}")
    print("")

Trying model with 10 estimator...
Model accuracy on test set: 0.7894736842105263

Trying model with 20 estimator...
Model accuracy on test set: 0.8157894736842105

Trying model with 30 estimator...
Model accuracy on test set: 0.8157894736842105

Trying model with 40 estimator...
Model accuracy on test set: 0.868421052631579

Trying model with 50 estimator...
Model accuracy on test set: 0.8026315789473685

Trying model with 60 estimator...
Model accuracy on test set: 0.8552631578947368

Trying model with 70 estimator...
Model accuracy on test set: 0.8026315789473685

Trying model with 80 estimator...
Model accuracy on test set: 0.8289473684210527

Trying model with 90 estimator...
Model accuracy on test set: 0.8289473684210527



# it is best practice to test different hyperparameters with a validation set or cross-validation

In [32]:
from sklearn.model_selection import cross_val_score

#Try different numbers of estimators with cross validation and no cross validation
np.random.seed(42)
for i in range(10, 100, 10):
    print(f"Trying model with {i} estimator...")
    model = RandomForestClassifier(n_estimators = i).fit(X_train, y_train)
    print(f"Model accuracy on test set: {model.score(X_test, y_test)}")
    print(f"Cross Validation score: {np.mean(cross_val_score(model, X, y, cv=5))*100}%")
    print("")

Trying model with 10 estimator...
Model accuracy on test set: 0.7894736842105263
Cross Validation score: 78.53551912568305%

Trying model with 20 estimator...
Model accuracy on test set: 0.881578947368421
Cross Validation score: 79.84699453551912%

Trying model with 30 estimator...
Model accuracy on test set: 0.8289473684210527
Cross Validation score: 80.50819672131148%

Trying model with 40 estimator...
Model accuracy on test set: 0.8026315789473685
Cross Validation score: 82.15300546448088%

Trying model with 50 estimator...
Model accuracy on test set: 0.8289473684210527
Cross Validation score: 81.1639344262295%

Trying model with 60 estimator...
Model accuracy on test set: 0.8157894736842105
Cross Validation score: 83.47540983606557%

Trying model with 70 estimator...
Model accuracy on test set: 0.868421052631579
Cross Validation score: 81.83060109289617%

Trying model with 80 estimator...
Model accuracy on test set: 0.8289473684210527
Cross Validation score: 82.81420765027322%

Try

# 6. Save the model for later use

In [33]:
import pickle

pickle.dump(model, open("models/random_forest_model_1.pkl", "wb"))

In [34]:
# load a saved model and make single prediction
model = pickle.load(open("models/random_forest_model_1.pkl", "rb"))
model.predict(X_test)

array([1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1,
       1, 1, 0, 1, 0, 1, 1, 0, 0, 0], dtype=int64)

-------------