# Introduction to tensorflow

A scalar is known as a rank 0 tensor. Because it has no dimensions (it's just a number).
> 🔑 Note: The important point is knowing tensors can have an unlimited range of dimensions (the exact amount will depend on what data you're representing).

In [1]:
import tensorflow as tf
print(tf.__version__)

2.4.1


In [ ]:
# create tensors with tf.constant()
scaler = tf.constant(7)
scaler

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# check the number of dimensions in tensor
scaler.ndim

0

In [ ]:
# create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
# check the dimensions of vector
vector.ndim

1

In [ ]:
# create a matrix (has more than 1 dimensions)
matrix = tf.constant([
    [10, 7],
    [7, 10]
])

matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
# create another matrix
another_matrix = tf.constant([
        [10, 7],
        [7, 10],
        [1.0, 9.0]],
        dtype=tf.float16
)

another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 7., 10.],
       [ 1.,  9.]], dtype=float16)>

In [ ]:
another_matrix.ndim

2

In [ ]:
# Let's creat a tensor
tensor = tf.constant([[[1,2,3], [4,5,6]], [[7,8,9], [10, 11, 12]], [[13, 14, 15], [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3

# What we have created so far:
- **scalar**: a single number.
- **vector**: a number with direction (e.g. wind speed with direction).
- **matrix**: a 2-dimensional array of numbers.
- **tensor**: an n-dimensional arrary of numbers (where n can be any number, a 0-dimension tensor is a scalar, a 1-dimension tensor is a vector).

-----


# Creating tensor with `tf.Variable()`

You can also (although you likely rarely will, because often, when working with data, tensors are created for you automatically) create tensors using tf.Variable().

The difference between `tf.Variable()` and `tf.constant()` is tensors created with `tf.constant()` are immutable (can't be changed, can only be used to create a new tensor), where as, tensors created with `tf.Variable() `are mutable (can be changed).

In [ ]:
# create same tensor with tf.variable() as above
changable_tensor = tf.Variable([10, 7])
unchangable_tensor = tf.constant([10, 7])

changable_tensor, unchangable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
# Let's try change one the elements in changable tensor
changable_tensor[0].assign(7)
changable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
unchangable_tensor[0].assign(7) # we can't change constant value
unchangable_tensor

AttributeError: ignored

Which one should you use? `tf.constant()` or `tf.Variable()`?

It will depend on what your problem requires. However, most of the time, TensorFlow will automatically choose for you (when loading data or modelling data).

-----

# Creating Random Tensors
Tensors of arbitary size which contain random numbers.

In [ ]:
# create two random tensors
random_1 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1 = random_1.normal(shape=(3, 2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [ ]:
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3, 2))
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [ ]:
# are they equal?
random_1 == random_2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

-----

# Shuffling the order elements in  tensor
- we want to shuffle the order of elements so that inherent order of data doesn't affect the learning
- **if we want to shuffle the data and make them in same order, we need to use both operational level and global level seed.**

### Global vs Operation Level Seed

`tf.random.set_seed(42)` sets the global seed, and the seed parameter in `tf.random.shuffle(seed=42)` sets the operation seed.

- this is helpful as we want to reproduce our expirement sometimes.

> 4. If both the global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence."

### Wait, why would you want to do that?

Let's say you working with 15,000 images of cats and dogs and the first 10,000 images of were of cats and the next 5,000 were of dogs. This order could effect how a neural network learns (it may overfit by learning the order of the data), instead, it might be a good idea to move your data around.

In [ ]:
not_shuffle = tf.constant([[10, 7], [1, 2], [3, 4]])
not_shuffle.ndim

2

In [ ]:
# shuffle our tensor
# we can see that shuffling make the first dimension shuffle
after_shuffled = tf.random.shuffle(not_shuffle)
after_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 1,  2]], dtype=int32)>

In [ ]:
after_shuffled = tf.random.shuffle(not_shuffle, seed=42)
after_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 1,  2],
       [ 3,  4]], dtype=int32)>

In [ ]:
tf.random.set_seed(42)
after_shuffled = tf.random.shuffle(not_shuffle)
after_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 1,  2],
       [ 3,  4],
       [10,  7]], dtype=int32)>

In [ ]:
after_shuffled = tf.random.shuffle(not_shuffle)
after_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 1,  2]], dtype=int32)>

## Note: 

`tf.random.set_seed(42)` sets the global seed, and the seed parameter in `tf.random.shuffle(seed=42)` sets the operation seed.

> 4. If both the global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence."

In [ ]:
# Shuffle in the same order every time

# Set the global random seed
tf.random.set_seed(42)

# Set the operation random seed
# tf.random.shuffle(not_shuffle)
tf.random.shuffle(not_shuffle, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 1,  2],
       [ 3,  4]], dtype=int32)>

In [ ]:
# Set the global random seed
tf.random.set_seed(42) # if you comment this out you'll get different results

# Set the operation random seed
tf.random.shuffle(not_shuffle)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 1,  2],
       [ 3,  4],
       [10,  7]], dtype=int32)>

## Exercise: create 5 random tensors and shuffle them
- we can see that using operation level seed will produce randomly shuffled every time we re-run the line.
- However, after setting global level random seed, we can see that no matter how many time we re-run this block of code, it doesn't change the seqeuence at all.

In [2]:
tf1 = tf.constant([[3, 4], [5, 6], [1,2]])
tf1

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6],
       [1, 2]], dtype=int32)>

#### operation level random seed

In [5]:
tf.random.shuffle(tf1, seed=42) # operation level random seed
# we can see that this will produce randomly shuffled every time we re-run the line

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6],
       [1, 2]], dtype=int32)>

#### global level random seed

In [7]:
tf.random.set_seed(42) # global level random seed
tf.random.shuffle(tf1, seed=41)

# after setting global level random seed, we can see that no matter how many time we re-run this block of code, it doesn't change the seqeuence at all.

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[5, 6],
       [1, 2],
       [3, 4]], dtype=int32)>

------

# Creating tensors from NumPy arrays



In [8]:
# create a tensor of ones
tf.ones(shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [9]:
# create a tensor of zeros
tf.zeros(shape=(3, 5))

<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

In [10]:
tf.zeros([3, 5])

<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

## Turn Numpy array to Tensor
The main difference between Numpy arrys and Tensors is that Tensors can be run on GPU computing.

In [11]:
# you can also turn Numpy array to tensors
import numpy as np

numpy_A = np.arange(1, 25, dtype=np.int32)
numpy_A

# X = tf.constant(matrix) # capital for matrix or tensor
# y = tf.constant(vector) # non capital for vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [12]:
A = tf.constant(numpy_A)
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [13]:
A = tf.constant(numpy_A, shape=(2, 3, 4))
B = tf.constant(numpy_A)

A, B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

In [15]:
2 * 3 * 4

24

In [16]:
A = tf.constant(numpy_A, shape=(8, 3))
A

<tf.Tensor: shape=(8, 3), dtype=int32, numpy=
array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24]], dtype=int32)>

In [17]:
A.ndim

2

-----

# Getting information from tensors (shape, rank, size) / Tensors Attributes

There will be times when we'll want to get different pieces of information from our tensors, in particuluar, we need now the following tensor vocabulary:

- **Shape**: The length (number of elements) of each of the dimensions of a tensor. `tensor.shape`
- **Rank**: The number of tensor dimensions. A scalar has rank 0, a vector has rank 1, a matrix is rank 2, a tensor has rank n. `tensor.ndim`
- **Axis or Dimension**: A particular dimension of a tensor. `tensor[0], tensor[:, 1]`
- **Size**: The total number of items in the tensor. `tf.size(tensor)`

We'll use these especially when you're trying to line up the shapes of our data to the shapes of our model. For example, making sure the shape of our image tensors are the same shape as our models input layer.

In [18]:
# Create a rank 4 tensor (4 dimensions)
rank4_tensor = tf.zeros(shape=[2, 3, 4, 5])
rank4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [19]:
rank4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [20]:
rank4_tensor[1]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [21]:
rank4_tensor.shape

TensorShape([2, 3, 4, 5])

In [22]:
rank4_tensor.ndim

4

In [24]:
tf.size(rank4_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=120>

In [25]:
2 * 3 * 4 * 5

120

## Get various attributes of tensors


In [28]:
# Get various attributes of tensors
print('DataType of every element: ', rank4_tensor.dtype)
print('Number of dimensions (rank): ', rank4_tensor.ndim)
print('Shape of tensor: ', rank4_tensor.shape)
print('Elements along the axis 0: ', rank4_tensor.shape[0]) # refer to the shape of the tensor and check the first index
print('Elements along the last axis: ', rank4_tensor.shape[-1])
print('Total elements in our tensor: ', tf.size(rank4_tensor))
print('Total elements in our tensor: ', tf.size(rank4_tensor).numpy()) # # .numpy() converts to NumPy array

DataType of every element:  <dtype: 'float32'>
Number of dimensions (rank):  4
Shape of tensor:  (2, 3, 4, 5)
Elements along the axis 0:  2
Elements along the last axis:  5
Total elements in our tensor:  tf.Tensor(120, shape=(), dtype=int32)
Total elements in our tensor:  120


----

# Indexing and Expanding Tensors

You can also index tensors just like Python lists.

In [32]:
somelist = [1, 2, 3, 4]
somelist[:2]

[1, 2]

In [31]:
# get the first 2 elements of each dimensions
rank4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [35]:
rank4_tensor.shape

TensorShape([2, 3, 4, 5])

In [40]:
# get the first element from each dimension , except for the final one
rank4_tensor[:1, :1, :1, :1]

<tf.Tensor: shape=(1, 1, 1, 1), dtype=float32, numpy=array([[[[0.]]]], dtype=float32)>

In [41]:
rank4_tensor[:, :1, :1, :1]

<tf.Tensor: shape=(2, 1, 1, 1), dtype=float32, numpy=
array([[[[0.]]],


       [[[0.]]]], dtype=float32)>

In [42]:
rank4_tensor[:1, :, :1, :1]

<tf.Tensor: shape=(1, 3, 1, 1), dtype=float32, numpy=
array([[[[0.]],

        [[0.]],

        [[0.]]]], dtype=float32)>

In [43]:
rank4_tensor[:1, :1, :, :1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [44]:
rank4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [49]:
# create a rank2 tensor (2 dimensions)
rank2_tensor = tf.constant([[10, 7], 
                                      [3, 4]])
rank2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [50]:
rank2_tensor.shape, rank2_tensor.ndim

(TensorShape([2, 2]), 2)

In [53]:
# let's get last item of each row of our rank2 tensor
rank2_tensor[: , -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [54]:
# if we want to add additional dimension
rank2_tensor[: , -1:]

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[7],
       [4]], dtype=int32)>

## Add in extra dimension to our rank2tensor
`...` means for every axis
There are 2 ways to do this.
+ tf.newaxis()
+ tf.expand_dims()

In [55]:
# Add in extra dimension to our rank2tensor
rank3_tensor = rank2_tensor[..., tf.newaxis] # same as [:, :, :, tf.newaxis]
rank3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [57]:
# Alternative to tf.newaxis
tf.expand_dims(rank2_tensor, axis=-1) # -1 means expands to last axis

# so from (2,2) became (2,2,1) , new 1 dimension to last axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [62]:
tf.expand_dims(rank2_tensor, axis=0)

# so from (2,2) became (1,2,2) , new 1 dimension to first axis or 0 - axis

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

In [63]:
tf.expand_dims(rank2_tensor, axis=1)

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[10,  7]],

       [[ 3,  4]]], dtype=int32)>


-----------

# Manipulating tensors with Basic Operations

Finding patterns in tensors (numberical representation of data) requires manipulating them.

Again, when building models in TensorFlow, much of this pattern discovery is done for you.

## Basic operations
You can perform many of the basic mathematical operations directly on tensors using Pyhton operators such as, +, -, *.