# NumPy

In [1]:
import numpy as np

In [3]:
# set seed for reproducivity
np.random.seed(seed=1234)

# Basic

### Scalar

In [11]:

x = np.array(6)
x

array(6)

In [12]:
x.ndim, x.shape, x.size, x.dtype

(0, (), 1, dtype('int32'))

### Vector

In [13]:

x = np.array([1.3, 2.2, 1.7])
x

array([1.3, 2.2, 1.7])

In [14]:
x.ndim, x.shape, x.size, x.dtype

(1, (3,), 3, dtype('float64'))

### Matrix

In [16]:

x = np.array([[1, 2], [3, 4]])
x

array([[1, 2],
       [3, 4]])

In [17]:
x.ndim, x.shape, x.size, x.dtype

(2, (2, 2), 4, dtype('int32'))

### 3-D Tensor

In [19]:
x = np.array([[[1,2], [3,4]], [[5, 6], [7,8]]])
x

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [20]:
x.ndim, x.shape, x.size, x.dtype

(3, (2, 2, 2), 8, dtype('int32'))

### Creating Tensors Quickly

In [21]:
np.zeros((2, 2))

array([[0., 0.],
       [0., 0.]])

In [22]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [23]:
np.eye((2))

array([[1., 0.],
       [0., 1.]])

In [26]:
np.random.random((2,2))

array([[0.43772774, 0.78535858],
       [0.77997581, 0.27259261]])

------

# Indexing

### Indexing

In [27]:
x = np.array([1, 2, 3])
x

array([1, 2, 3])

In [28]:
x[0]

1

In [29]:
x[0] = 0
x

array([0, 2, 3])

### Slicing

In [30]:
x = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [37]:
print('x column 1: ', x[: , 1])
print('x row 0: ', x[0, :])
print('x row 0,1 & cols 1,2: \n', x[0:2, 1:3])

x column 1:  [ 2  6 10]
x row 0:  [1 2 3 4]
x row 0,1 & cols 1,2: 
 [[2 3]
 [6 7]]


### Integer array indexing

In [38]:
print(x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [40]:
rows_to_get = np.array([0, 1, 2])
print('rows to get: ', rows_to_get)

cols_to_get = np.array([0, 2, 1])
print('cols to get: ', cols_to_get)

rows to get:  [0 1 2]
cols to get:  [0 2 1]


In [41]:
print('Indexed Values: ', x[rows_to_get, cols_to_get])

Indexed Values:  [ 1  7 10]


### Boolean Array Indexing

In [42]:
x = np.array([[1, 2], [3, 4], [5, 6]])
x

array([[1, 2],
       [3, 4],
       [5, 6]])

In [44]:
print('x > 2: \n', x > 2)

x > 2: 
 [[False False]
 [ True  True]
 [ True  True]]


In [45]:
print('x[x > 2]: \n', x[x>2])

x[x > 2]: 
 [3 4 5 6]


# Arithmetic

### Basic Maths

In [47]:
x = np.array([[1, 2], [3, 4]], dtype=np.float64)
y = np.array([[1, 2], [3, 4]], dtype=np.float64)

In [49]:
x, y

(array([[1., 2.],
        [3., 4.]]),
 array([[1., 2.],
        [3., 4.]]))

In [48]:
np.add(x, y)

array([[2., 4.],
       [6., 8.]])

In [50]:
np.subtract(x, y)

array([[0., 0.],
       [0., 0.]])

In [51]:
np.multiply(x, y)

array([[ 1.,  4.],
       [ 9., 16.]])

In [52]:
np.divide(x,y)

array([[1., 1.],
       [1., 1.]])

# Dot Product

### Dot Product

In [54]:
a = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.float64)
b = np.array([[7, 8], [9, 10], [11, 12]], dtype=np.float64)

a, b

(array([[1., 2., 3.],
        [4., 5., 6.]]),
 array([[ 7.,  8.],
        [ 9., 10.],
        [11., 12.]]))

In [57]:
c = a.dot(b)
c

array([[ 58.,  64.],
       [139., 154.]])

In [58]:
print(f'{a.shape} . {b.shape} = {c.shape}')

(2, 3) . (3, 2) = (2, 2)


# Axis Operations

### Sum across dimensions

In [59]:
x = np.array([[1, 2], [3, 4]])
x

array([[1, 2],
       [3, 4]])

In [60]:
print('sum all : ', np.sum(x))
print('sum axis=0: ', np.sum(x, axis=0)) # sum across row
print('sum axis=1: ', np.sum(x, axis=1)) # sum across columns

sum all :  10
sum axis=0:  [4 6]
sum axis=1:  [3 7]


### Min / Max

In [61]:
x = np.array([[1, 2, 3], [4, 5, 6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [62]:
print('min: ', x.min())
print('max: ', x.max())
print('min axis=0:', x.min(axis=0))
print('min axis=1:', x.min(axis=1))

min:  1
max:  6
min axis=0: [1 2 3]
min axis=1: [1 4]


# Broadcast

In [64]:
x = np.array([1, 2]) # vector
y = np.array(3) # scalar

z = x + y
z

array([4, 5])

# Transpose

In [66]:
# usually used it to change the dimensions of tensors
x = np.array([[1, 2, 3], [4, 5, 6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [68]:
y = np.transpose(x, (1,0)) # flip dimensions at index 0 and 1
y

array([[1, 4],
       [2, 5],
       [3, 6]])

In [70]:
x.shape, y.shape

((2, 3), (3, 2))

# Reshape

### Reshaping

In [77]:
x = np.array([[1, 2, 3, 4, 5, 6]])
x

array([[1, 2, 3, 4, 5, 6]])

In [78]:
x.shape

(1, 6)

In [80]:
y = np.reshape(x, (2, 3))
y, y.shape

(array([[1, 2, 3],
        [4, 5, 6]]),
 (2, 3))

In [81]:
z = np.reshape(x, (2, -1)) # We can also use -1 on a dimension and NumPy will infer the dimension based on our input tensor.
z, z.shape

(array([[1, 2, 3],
        [4, 5, 6]]),
 (2, 3))

In [82]:
x = np.array([[[1, 1, 1, 1], [2, 2, 2, 2], [3, 3, 3, 3]],
              [[10, 10, 10, 10], [20, 20, 20, 20], [30, 30, 30, 30]]])
print ("x:\n", x)
print ("x.shape: ", x.shape)

x:
 [[[ 1  1  1  1]
  [ 2  2  2  2]
  [ 3  3  3  3]]

 [[10 10 10 10]
  [20 20 20 20]
  [30 30 30 30]]]
x.shape:  (2, 3, 4)


In [84]:
y = np.transpose(x, (1,0,2))
y

array([[[ 1,  1,  1,  1],
        [10, 10, 10, 10]],

       [[ 2,  2,  2,  2],
        [20, 20, 20, 20]],

       [[ 3,  3,  3,  3],
        [30, 30, 30, 30]]])

In [85]:
z_correct = np.reshape(y, (y.shape[0], -1))

In [86]:
z_correct

array([[ 1,  1,  1,  1, 10, 10, 10, 10],
       [ 2,  2,  2,  2, 20, 20, 20, 20],
       [ 3,  3,  3,  3, 30, 30, 30, 30]])

# Expanding / Reducing

In [87]:
# Adding dimensions
x = np.array([[1, 2, 3], [4, 5, 6]])
x, x.shape

(array([[1, 2, 3],
        [4, 5, 6]]),
 (2, 3))

In [90]:
y = np.expand_dims(x, 1) # expand dim 1

print ("y: \n", y)
print ("y.shape: ", y.shape)   # notice extra set of brackets are added

y: 
 [[[1 2 3]]

 [[4 5 6]]]
y.shape:  (2, 1, 3)


In [91]:
# Removing dimenisons
x = np.array([[[1,2,3]],[[4,5,6]]])
x, x.shape

(array([[[1, 2, 3]],
 
        [[4, 5, 6]]]),
 (2, 1, 3))

In [92]:
y = np.squeeze(x, 1) # squeeze dim 1
y

array([[1, 2, 3],
       [4, 5, 6]])

In [93]:
y.shape

(2, 3)