# Stimulating Coin Flips

In [1]:
import numpy as np

In [2]:
np.random.rand()

0.5635332470082699

## Flipping coins x times

In [5]:
#100 times coin flip
np.random.randint(5, size = 100)

array([2, 4, 4, 1, 3, 2, 1, 3, 4, 1, 4, 3, 4, 0, 2, 1, 2, 1, 2, 2, 1, 3,
       2, 0, 1, 3, 3, 0, 2, 4, 4, 4, 1, 4, 3, 2, 1, 2, 3, 4, 0, 0, 3, 0,
       4, 2, 3, 3, 0, 3, 1, 3, 0, 3, 0, 2, 1, 0, 3, 1, 4, 1, 2, 3, 1, 0,
       0, 2, 2, 1, 0, 2, 2, 2, 4, 1, 1, 4, 3, 2, 3, 2, 0, 3, 1, 0, 1, 1,
       3, 2, 4, 1, 0, 4, 3, 4, 0, 4, 3, 1])

## Flipping Weighted Coins

In [6]:
coin_faces = [0, 1]
# heads for 80%, tail for 20%
np.random.choice(coin_faces, size = 100, p = [0.8, 0.2])

array([0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0])

In [7]:
np.random.choice(coin_faces, size = 100, p = [0.8, 0.2]).mean()

0.19

----------

## More Exercises

In [8]:
# outcome of one coin flip
np.random.randint(2)

0

In [12]:
# outcomes of ten thousand coin flips
np.random.randint(2, size = 10000)

array([0, 0, 0, ..., 1, 1, 1])

In [13]:
# mean outcome of ten thousand coin flips
np.random.randint(2, size = 10000).mean()

0.5017

### using choice method for Biased Coin

In [14]:
# outcome of one coin flip, using choice
np.random.choice([0,1])

0

In [16]:
# outcome of ten thousand coin flips
np.random.choice([0,1], size = 10000)

array([1, 0, 1, ..., 1, 1, 0])

In [17]:
# mean outcome of ten thousand coin flips
np.random.choice([0,1], size = 10000).mean()

0.5001

In [18]:
# outcomes of ten thousand biased coin flips
np.random.choice([0,1], size = 10000, p = [0.8, 0.2])

array([0, 0, 0, ..., 1, 0, 0])

In [19]:
# mean outcome of ten thousand biased coin flips
np.random.choice([0, 1], size = 10000, p =[0.8, 0.2]).mean()

0.1996

-------------

# Probability Quiz

## Coin Flips and Die Rolls
0 represents heads. 1 represents tails.

In [20]:
import numpy as np

### 1.Two fair coin flips produce exactly two heads

In [31]:
# simulate 1 million tests of two fair coin flips
results = np.random.randint(2, size =(1000000, 2))

# sums of all tests
total_sum = results.sum(axis = 1)

# proportion of tests that produced exactly two heads
(total_sum == 0).mean()

0.24978

### 2. Three fair coin flips produce exactly one head

In [38]:
# simulate 1 million tests of three fair coin flips
results = np.random.randint(2, size = (1000000, 3))

# sums of all tests
total_sum = results.sum(axis = 1)

# proportion of tests that produced exactly one head
(total_sum == 2).mean()

0.375104

### 3. Three biased coin flips with P(H) = 0.6 produce exactly one head

In [37]:
# simulate 1 million tests of three biased coin flips
# hint: use np.random.choice()
results = np.random.choice([0,1] , size=(1000000, 3), p = [0.6, 0.4])

# sums of all tests
total_sum = results.sum(axis = 1)

# proportion of tests that produced exactly one head
(total_sum == 2).mean()

0.288859

### 4. A die rolls an even number

In [46]:
# simulate 1 million tests of one die roll
results = np.random.choice(np.arange(1,7), size = 1000000)
results

# proportion of tests that produced an even number
# len([i for i in tests if i%2 == 0])/int(1e6)
(results % 2 == 0).mean()

0.499556

In [47]:
len([i for i in results if i%2 == 0])/int(1e6)

0.499556

### 5. Two dice roll a double

In [51]:
# simulate the first million die rolls
results_one = np.random.choice(np.arange(1, 7), size = int(1e6))

# simulate the second million die rolls
results_two = np.random.choice(np.arange(1, 7), size = int(1e6))



# proportion of tests where the 1st and 2nd die rolled the same number
# len([(i, j) for (i,j) in zip(first, second) if i == j]) / int(1e6)
(results_one == results_two).mean()


0.166003