In [1]:
import numpy as np

In [2]:
my_list = [1,2,3]

In [3]:
type(my_list)

list

In [4]:
np.array(my_list)

array([1, 2, 3])

In [5]:
my_matrix = [[1,2,3], [4,5,6]]

In [6]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0, 101, 2)

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [9]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [10]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [12]:
np.ones(2)

array([1., 1.])

In [13]:
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [14]:
np.linspace(0, 10, 3) # give me 3 points which are linearly spaced between 0 and 10 (inclusiv)

array([ 0.,  5., 10.])

In [15]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [16]:
np.linspace(0, 10, 11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [17]:
 len(np.linspace(0, 10, 21))

21

In [18]:
# identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [19]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [25]:
np.random.rand() # shift + tab to see the help

0.311462391207728

In [26]:
np.random.rand(2)

array([0.91735446, 0.90742942])

In [28]:
np.random.rand(1)

array([0.84478731])

In [29]:
np.random.rand(5,2)

array([[0.28876869, 0.90632685],
       [0.45045825, 0.2309856 ],
       [0.91182512, 0.9200919 ],
       [0.10135301, 0.47278034],
       [0.72683553, 0.89819102]])

In [32]:
np.random.randn(10) # give 10 numbers which have standard normal distribution

array([ 4.78566825e-01,  2.47083199e-03,  4.27663494e-01, -2.36098344e+00,
       -1.40585325e+00, -7.04658056e-01, -4.80572433e-02, -1.33141525e+00,
        1.31392656e+00,  3.09586936e+00])

In [33]:
np.random.randn(5,2)

array([[-9.82943946e-01, -2.68843263e-01],
       [ 1.20181378e+00, -3.61621661e-01],
       [-4.22416580e-02,  2.12164481e+00],
       [ 1.53412105e-03, -1.13610964e+00],
       [-6.84364593e-01, -6.28888602e-01]])

In [35]:
np.random.randint(1, 10, (2,5)) # only return whole integers

array([[7, 5, 6, 1, 1],
       [7, 6, 8, 6, 3]])

In [36]:
np.random.randint(1, 50, 5)

array([28,  9, 23,  4,  8])

In [40]:
# seed allow to set specific random numbers
# seeding and random generator should be in same cell

np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

------

In [41]:
arr = np.arange(0,25)

In [42]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [43]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [54]:
arr.shape

(25,)

In [44]:
# max, min

In [45]:
random_array = np.random.randint(0, 101, 10)

In [46]:
random_array

array([82, 86, 74, 74, 87, 99, 23,  2, 21, 52])

In [47]:
random_array.max()

99

In [48]:
random_array.min()

2

In [49]:
# if we want index of min, max
random_array.argmax()

5

In [51]:
random_array.argmin()

7

In [52]:
random_array.dtype

dtype('int32')

In [53]:
random_array.shape

(10,)

In [58]:
random_array = random_array.reshape(2,5)

In [59]:
random_array.shape

(2, 5)

------------

### Exercise

In [60]:
# TASK: Create a numpy array called myarray which consists of 101 evenly linearly spaced points between 0 and 10.
# MAKE SURE TO READ THE FULL INSTRUCTIONS ABOVE CAREFULLY, AS THE EVALUATION SCRIPT IS VERY STRICT.

# import ?
# myarray = ?

In [62]:
import numpy as np
myarray = np.linspace(0, 10, 101)
print(myarray)

[ 0.   0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9  1.   1.1  1.2  1.3
  1.4  1.5  1.6  1.7  1.8  1.9  2.   2.1  2.2  2.3  2.4  2.5  2.6  2.7
  2.8  2.9  3.   3.1  3.2  3.3  3.4  3.5  3.6  3.7  3.8  3.9  4.   4.1
  4.2  4.3  4.4  4.5  4.6  4.7  4.8  4.9  5.   5.1  5.2  5.3  5.4  5.5
  5.6  5.7  5.8  5.9  6.   6.1  6.2  6.3  6.4  6.5  6.6  6.7  6.8  6.9
  7.   7.1  7.2  7.3  7.4  7.5  7.6  7.7  7.8  7.9  8.   8.1  8.2  8.3
  8.4  8.5  8.6  8.7  8.8  8.9  9.   9.1  9.2  9.3  9.4  9.5  9.6  9.7
  9.8  9.9 10. ]
