In [1]:
import numpy as np

In [12]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Indexing and Slicing

In [13]:
arr[8]

8

In [14]:
arr[1:7]

array([1, 2, 3, 4, 5, 6])

In [15]:
arr[:7]

array([0, 1, 2, 3, 4, 5, 6])

In [16]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

# Broadcating

In [17]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
# assign 100 to position of 0 to 5 by using broadcasting
arr[0:5] = 100

In [19]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [21]:
# slice of array and assign to new variable, act as pointer
slice_of_arr = arr[0:5]

In [22]:
slice_of_arr

array([100, 100, 100, 100, 100])

In [23]:
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99, 99])

In [25]:
# when we check original one, it got changed too. (broadcating effects it.)
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [26]:
# to avoid this
array_copy = arr.copy()

In [27]:
array_copy

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [28]:
array_copy[0:5] = 200
array_copy

array([200, 200, 200, 200, 200,   5,   6,   7,   8,   9,  10])

In [29]:
# original one doesn't get affected
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

-------

# 2 dimensional arrays

In [31]:
arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [32]:
arr_2d.shape

(3, 3)

In [34]:
arr_2d[0] # first row

array([ 5, 10, 15])

In [35]:
arr_2d[0][1] # row, column

10

In [37]:
# same as above
arr_2d[0,1]

10

In [39]:
# slicing
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

# Conditional Selection

In [41]:
arr = np.arange(1, 11)

In [42]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [44]:
arr[arr > 4]

array([ 5,  6,  7,  8,  9, 10])

---------

# Exercise

In [47]:
# TASK: Use numpy to check how many rolls were greater than 2. For example if dice_rolls=[1,2,3] then the answer is 1.
# NOTE: Many different ways to do this! Your final answer should be an integer.
# MAKE SURE TO READ THE FULL INSTRUCTIONS ABOVE CAREFULLY, AS THE EVALUATION SCRIPT IS VERY STRICT.

import numpy as np
dice_rolls = np.array([3, 1, 5, 2, 5, 1, 1, 5, 1, 4, 2, 1, 4, 5, 3, 4, 5, 2, 4, 2, 6, 6, 3, 6, 2, 3, 5, 6, 5])

# total_rolls_over_two = # This should be a single integer

In [48]:
total_rolls_over_two = len(dice_rolls[dice_rolls > 2])
print(total_rolls_over_two)

19
