Ref: https://realpython.com/linear-regression-in-python/

# 1) Linear Regression

## 1) Import packages and classes

In [2]:
import numpy as np
from sklearn.linear_model import LinearRegression

## 2) Provide Data

In [3]:
x = np.array([5, 15, 25, 35, 45, 55]).reshape((-1, 1)) # one column and as many rows as possible
y = np.array([5, 20, 14, 32, 22, 38])

In [6]:
print(x)
print(x.shape)

[[ 5]
 [15]
 [25]
 [35]
 [45]
 [55]]
(6, 1)


In [7]:
print(y)
print(y.shape)

[ 5 20 14 32 22 38]
(6,)


## 3) Create model and fit

In [8]:
lr = LinearRegression()

In [9]:
lr.fit(x, y)

LinearRegression()

## 4) Get Results

The coefficient of determination, denoted as 𝑅², tells you which amount of variation in 𝑦 can be explained by the dependence on 𝐱 using the particular regression model. Larger 𝑅² indicates a better fit and means that the model can better explain the variation of the output with different inputs.

The value 𝑅² = 1 corresponds to SSR = 0, that is to the perfect fit since the values of predicted and actual responses fit completely to each other.

In [10]:
r_sq = lr.score(x, y)
print('coefficient of determination: ', r_sq)

coefficient of determination:  0.7158756137479542


In [12]:
print('intercept: ', lr.intercept_)
print('slope: ', lr.coef_)

intercept:  5.633333333333329
slope:  [0.54]


-------

We can provide y as a two-dimensional array as well.

In [14]:
# New Model
lr_new_model = LinearRegression().fit(x, y.reshape(-1, 1))

print('intercept: ', lr_new_model.intercept_)
print('slope: ', lr_new_model.coef_)

intercept:  [5.63333333]
slope:  [[0.54]]


## 5) Predict Response

In [15]:
y_pred = lr.predict(x)
print('predicted response: ', y_pred)

predicted response:  [ 8.33333333 13.73333333 19.13333333 24.53333333 29.93333333 35.33333333]


In [16]:
# Another way to predict the predictions
# in this case we use, coef and intercept

y_pred = lr.coef_*x + lr.intercept_
print('predicted response: ', y_pred)

predicted response:  [[ 8.33333333]
 [13.73333333]
 [19.13333333]
 [24.53333333]
 [29.93333333]
 [35.33333333]]


 We can reduce the number of dimensions of x to one, these two approaches will yield the same result. 
 
 We can do this by replacing x with x.reshape(-1), x.flatten(), or x.ravel() when multiplying it with model.coef_.

In [19]:
x_new = np.arange(5).reshape(-1, 1)
print(x_new)

[[0]
 [1]
 [2]
 [3]
 [4]]


In [20]:
y_new = lr.predict(x_new)
print(y_new)

[5.63333333 6.17333333 6.71333333 7.25333333 7.79333333]


---------

# 2) Multiple Linear Regression

In [21]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [22]:
x =  [[0, 1], [5, 1], [15, 2], [25, 5], [35, 11], [45, 15], [55, 34], [60, 35]]
y = [4, 5, 20, 14, 32, 22, 38, 43]

x, y = np.array(x), np.array(y)

In [23]:
print(x)

[[ 0  1]
 [ 5  1]
 [15  2]
 [25  5]
 [35 11]
 [45 15]
 [55 34]
 [60 35]]


In [24]:
print(y)

[ 4  5 20 14 32 22 38 43]


In [25]:
lr = LinearRegression()

In [26]:
lr.fit(x, y)

LinearRegression()

We obtain the value of 𝑅² using .score() and the values of the estimators of regression coefficients with .intercept_ and .coef_. Again, .intercept_ holds the bias 𝑏₀, while now .coef_ is an array containing 𝑏₁ and 𝑏₂ respectively.

In [27]:
r_sq = lr.score(x, y)
print('coefficient of determination: ', r_sq)

print('intercept: ', lr.intercept_)
print('slope: ', lr.coef_)

coefficient of determination:  0.8615939258756776
intercept:  5.5225792751981935
slope:  [0.44706965 0.25502548]


In [28]:
y_pred = lr.predict(x)

print('predictions: ', y_pred)

predictions:  [ 5.77760476  8.012953   12.73867497 17.9744479  23.97529728 29.4660957
 38.78227633 41.27265006]


In [31]:
# can also obtain the same thing as above
# but we need to sum up along the axis 1 because we have multiple dimensions

y_pred = np.sum(lr.coef_*x, axis=1) + lr.intercept_

print('predictions: ', y_pred)

predictions:  [ 5.77760476  8.012953   12.73867497 17.9744479  23.97529728 29.4660957
 38.78227633 41.27265006]


In [32]:
# predictions on new data
x_new = np.arange(10).reshape((-1, 2))

print(x_new)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [33]:
new_predictions = lr.predict(x_new)

print('new predictions: ', new_predictions)

new predictions:  [ 5.77760476  7.18179502  8.58598528  9.99017554 11.3943658 ]


---------------

# 3) Polynomial Regression

## 1) Import packages and Classes

In [34]:
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures

## 2.1) Provide data

In [35]:
x = np.array([5, 15, 25, 35, 45, 55]).reshape((-1, 1))
y = np.array([15, 11, 2, 8, 25, 32])

In [36]:
print(x)
print(y)

[[ 5]
 [15]
 [25]
 [35]
 [45]
 [55]]
[15 11  2  8 25 32]


## 2.2) Transfrom Input data
This is additional step for Polynomial Regression.


The variable transformer refers to an instance of PolynomialFeatures which you can use to transform the input x.

You can provide several optional parameters to PolynomialFeatures:

- **degree** is an integer (2 by default) that represents the degree of the polynomial regression function.
- **interaction_only** is a Boolean (False by default) that decides whether to include only interaction features (True) or all features (False).
- **include_bias** is a Boolean (True by default) that decides whether to include the bias (intercept) column of ones (True) or not (False).

In [38]:
transformer = PolynomialFeatures(degree=2, include_bias=False)

In [41]:
x_ = transformer.fit_transform(x)

The modified input array contains two columns: one with the original inputs and the other with their squares.

In [42]:
print(x_)

[[   5.   25.]
 [  15.  225.]
 [  25.  625.]
 [  35. 1225.]
 [  45. 2025.]
 [  55. 3025.]]


## 3) Create model and fit it

In [43]:
lr = LinearRegression()

In [44]:
lr.fit(x_, y)

LinearRegression()

## 4) Get Results

.score() returns 𝑅². Its first argument is also the modified input x_, not x. The values of the weights are associated to .intercept_ and .coef_: .intercept_ represents 𝑏₀, while .coef_ references the array that contains 𝑏₁ and 𝑏₂ respectively.

In [46]:
r_sq = lr.score(x_, y)

print('coefficient of determination: ', r_sq)
print('intercept: ', lr.intercept_)
print('coefficient / slope: ', lr.coef_)

coefficient of determination:  0.8908516262498563
intercept:  21.372321428571453
coefficient / slope:  [-1.32357143  0.02839286]


## Using `include_bias=True`

In [47]:
x_ = PolynomialFeatures(degree=2, include_bias=True).fit_transform(x)

In [48]:
print(x_)

[[1.000e+00 5.000e+00 2.500e+01]
 [1.000e+00 1.500e+01 2.250e+02]
 [1.000e+00 2.500e+01 6.250e+02]
 [1.000e+00 3.500e+01 1.225e+03]
 [1.000e+00 4.500e+01 2.025e+03]
 [1.000e+00 5.500e+01 3.025e+03]]


The first column of x_ contains ones, the second has the values of x, while the third holds the squares of x.


The intercept is already included with the leftmost column of ones, and you don’t need to include it again when creating the instance of LinearRegression. Thus, We can provide `fit_intercept=False`. This is how the next statement looks:

In [49]:
lr = LinearRegression(fit_intercept=False)

In [50]:
lr.fit(x_, y)

LinearRegression(fit_intercept=False)

In [52]:
r_sq = lr.score(x_, y)

print('coefficient of determination: ', r_sq)
print('intercept: ', lr.intercept_)
print('coefficients: ', lr.coef_)

coefficient of determination:  0.8908516262498563
intercept:  0.0
coefficients:  [21.37232143 -1.32357143  0.02839286]


We see that now .intercept_ is zero, but .coef_ actually contains 𝑏₀ as its first element. Everything else is the same.

## 5) Predict Response

In [53]:
y_pred = lr.predict(x_)

print('Predictions: ', y_pred)

Predictions:  [15.46428571  7.90714286  6.02857143  9.82857143 19.30714286 34.46428571]


------

#  4) several input variables - Polynomial Regression

In [54]:
# Step 1: Import class and packages
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures

In [55]:
# Step 2.1: Provide data
x = [[0, 1], [5, 1], [15, 2], [25, 5], [35, 11], [45, 15], [55, 34], [60, 35]]
y = [4, 5, 20, 14, 32, 22, 38, 43]

x, y = np.array(x), np.array(y)

In [57]:
# Step 2.2: Transform input data
x_ = PolynomialFeatures(degree=2, include_bias=False).fit_transform(x)

In [58]:
# Step 3: Create model and fit it
lr = LinearRegression()
lr.fit(x_, y)

LinearRegression()

In [60]:
# Step 4: Get results
r_sq = lr.score(x_, y)
intercept_, coefficients = lr.intercept_, lr.coef_

In [61]:
# Step 5: Predict
y_pred = lr.predict(x_)

In [63]:
print('coefficient of determination: ', r_sq)
print('intercept: ', intercept_)
print('coefficients: ', coefficients)

coefficient of determination:  0.9453701449127822
intercept:  0.8430556452397582
coefficients:  [ 2.44828275  0.16160353 -0.15259677  0.47928683 -0.4641851 ]


In [64]:
print('Predictions: ', y_pred)

Predictions:  [ 0.54047408 11.36340283 16.07809622 15.79139    29.73858619 23.50834636
 39.05631386 41.92339046]


We can also notice that polynomial regression yielded a higher coefficient of determination than multiple linear regression for the same problem. At first, we could think that obtaining such a large 𝑅² is an excellent result. It might be.

However, in real-world situations, having a complex model and 𝑅² very close to 1 might also be a sign of overfitting. 

---------

# 6) Advanced Linear Regression With statsmodels

We can implement linear regression in Python relatively easily by using the package statsmodels as well. Typically, this is desirable when there is a need for more detailed results.

## 1) Import Packages

In [65]:
import numpy as np
import statsmodels.api as sm

## 2) Provide Data and Transform inputs

In [66]:
x = [[0, 1], [5, 1], [15, 2], [25, 5], [35, 11], [45, 15], [55, 34], [60, 35]]
y = [4, 5, 20, 14, 32, 22, 38, 43]

x, y = np.array(x), np.array(y)

We need to add the column of ones to the inputs if you want statsmodels to calculate the intercept 𝑏₀. It doesn’t takes 𝑏₀ into account by default. 

In [67]:
x = sm.add_constant(x)

modified x has three columns: the first column of ones (corresponding to 𝑏₀ and replacing the intercept) as well as two columns of the original features.

In [68]:
print(x)

[[ 1.  0.  1.]
 [ 1.  5.  1.]
 [ 1. 15.  2.]
 [ 1. 25.  5.]
 [ 1. 35. 11.]
 [ 1. 45. 15.]
 [ 1. 55. 34.]
 [ 1. 60. 35.]]


## 3) Create Model and fit it

In [69]:
model = sm.OLS(y, x) # ordinary least squares is an instance of the class statsmodels.regression.linear_model.OLS

In [70]:
results = model.fit()

## 4) Get Results

In [71]:
print(results.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.862
Model:                            OLS   Adj. R-squared:                  0.806
Method:                 Least Squares   F-statistic:                     15.56
Date:                Sun, 16 May 2021   Prob (F-statistic):            0.00713
Time:                        11:36:11   Log-Likelihood:                -24.316
No. Observations:                   8   AIC:                             54.63
Df Residuals:                       5   BIC:                             54.87
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          5.5226      4.431      1.246      0.2

C:\Users\Phone Thiri Yadana\.conda\envs\venv-datascience\lib\site-packages\scipy\stats\stats.py:1603: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=8
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "


.rsquared holds `𝑅`².

.rsquared_adj represents` adjusted 𝑅²` (𝑅² corrected according to the number of input features).

.params refers the array with `𝑏₀, 𝑏₁, and 𝑏₂` respectively.

In [72]:
print('coefficient of determination: ', results.rsquared)
print('adjusted coefficient of determination: ', results.rsquared_adj)
print('regression coefficients: ', results.params)

coefficient of determination:  0.8615939258756776
adjusted coefficient of determination:  0.8062314962259487
regression coefficients:  [5.52257928 0.44706965 0.25502548]


## 5) Predict Response

In [73]:
print('Predictions: ', results.fittedvalues, sep='\n')

Predictions: 
[ 5.77760476  8.012953   12.73867497 17.9744479  23.97529728 29.4660957
 38.78227633 41.27265006]


In [74]:
pred = results.predict(x)

print('Predictions: ', pred, sep='\n')

Predictions: 
[ 5.77760476  8.012953   12.73867497 17.9744479  23.97529728 29.4660957
 38.78227633 41.27265006]


In [75]:
# predict new values
x_new = sm.add_constant(np.arange(10).reshape((-1, 2)))
print(x_new)

[[1. 0. 1.]
 [1. 2. 3.]
 [1. 4. 5.]
 [1. 6. 7.]
 [1. 8. 9.]]


In [76]:
y_new = results.predict(x_new)
print(y_new)

[ 5.77760476  7.18179502  8.58598528  9.99017554 11.3943658 ]
