<center><em>Copyright Pierian Data</em></center>
<center><em>For more information, visit us at <a href='http://www.pieriandata.com'>www.pieriandata.com</a></em></center>

# NumPy Indexing and Selection

In this lecture we will discuss how to select elements or groups of elements from an array.

In [1]:
import numpy as np

In [3]:
#Creating sample array
arr = np.arange(0, 11)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [5]:
#Get a value at an index
arr [5]

5

In [6]:
#Get values in a range
arr[1:5]

array([1, 2, 3, 4])

In [7]:
arr[:8]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [8]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

## Broadcasting

NumPy arrays differ from normal Python lists because of their ability to broadcast. With lists, you can only reassign parts of a list with new parts of the same size and shape. That is, if you wanted to replace the first 5 elements in a list with a new value, you would have to pass in a new 5 element list. With NumPy arrays, you can broadcast a single value across a larger set of values:

In [9]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
# set the first five elements to 100
#Setting a value with index range (Broadcasting)

arr[0:5] = 100

In [11]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [13]:
# Reset array, we'll see why I had to reset in  a moment
arr = np.arange(0, 11)

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
#Important notes on Slices
# slice of original array
slice_of_arr = arr[0:5]

#Show slice
slice_of_arr

array([0, 1, 2, 3, 4])

In [15]:
arr # original arry keeps the same though

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
#Change Slice, Now I want to set 99 to all elements of slice_of_arr
slice_of_arr[:] = 99

slice_of_arr

array([99, 99, 99, 99, 99])

Now note the changes also occur in our original array!

In [17]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

Data is not copied, it's a view of the original array! This avoids memory problems!

In [19]:
#To get a copy, need to be explicit
arr_copy = arr.copy()

In [20]:
arr_copy [:] = 1000
arr_copy

array([1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000])

In [21]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [12]:

arr_copy = arr.copy()

arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. I recommend using the comma notation for clarity.

In [22]:
arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])

arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [23]:
arr_2d.shape

(3, 3)

In [25]:
arr_2d[0]

array([ 5, 10, 15])

In [26]:
arr_2d[2]

array([35, 40, 45])

In [27]:
arr_2d[1][1]

25

In [28]:
#OR
arr_2d[1,1]

25

In [30]:
arr_2d[0,2]

15

In [32]:
#Indexing row
arr_2d[1]

array([20, 25, 30])

In [33]:
# Format is arr_2d[row][col] or arr_2d[row,col]

# Getting individual element value
arr_2d[1][0]

20

In [35]:
# Getting individual element value
arr_2d[1,0]

20

In [37]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [38]:
# 2D array slicing

#Shape (2,2) from top right corner

arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

In [39]:
#Shape bottom row
arr_2d[2]

array([35, 40, 45])

In [40]:
#Shape bottom row (Another way)
arr_2d[2, :]

array([35, 40, 45])

## More Indexing Help
Indexing a 2D matrix can be a bit confusing at first, especially when you start to add in step size. Try google image searching *NumPy indexing* to find useful images, like this one:

<img src= 'numpy_indexing.png' width=500/> Image source: http://www.scipy-lectures.org/intro/numpy/numpy.html

## Conditional Selection

This is a very fundamental concept that will directly translate to pandas later on, make sure you understand this part!

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [41]:
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
 # if greather > 4 then become True, otherwise False
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [44]:
bool_arr = arr > 4

In [45]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [46]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [48]:
arr[arr > 7]

array([ 8,  9, 10])

In [49]:
x = 2
arr[arr > x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

# Great Job!
