# NumPy

- NumPy is very fast as this speed comes from the nature of NumPy arrays being memory-efficient and from optimized algorithms used by NumPy for doing arithmetic, statistical, and linear algebra operations.
- it has multidimensional array data structures that can represent vectors and matrices.
- NumPy has a large number of optimized built-in mathematical functions
- NumPy holds same data type in its arrays , regardelss of string, number, etc


At the core of NumPy is the ndarray, where nd stands for n-dimensional. An ndarray is a multidimensional array of elements all of the same type. In other words, an ndarray is a grid that can take on many shapes and can hold either numbers or strings.


In [1]:
import time
import numpy as np

In [5]:
x = np.random.random(100000000)

In [6]:
start = time.time()
average = sum(x) / len(x)
print(f"time to compute {time.time()-start}")

time to compute 21.606374502182007


In [7]:
#using numpy
start = time.time()
average = np.mean(x)
print(f"time to compute {time.time()-start}")

time to compute 0.13408756256103516


## Creating and Saving NumPy

- rank 1 array : one dimensional array
- rank 2 array: two dimensional array
- rank n array: n dimensional array

In [8]:
import numpy as np
x = np.array([1,2,3,4,5])

In [10]:
print(x)
print(type(x))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [13]:
x.dtype

dtype('int32')

In [14]:
x.shape

(5,)

In [21]:
x.size

5

In [17]:
Y = np.array([[1,2,3,4,5], [6,7,8,9,10]])

In [18]:
Y.dtype

dtype('int32')

In [19]:
Y.shape

(2, 5)

In [20]:
Y.size

10

--------------
#### NumPy holds elements as same data type in its array

In [22]:
words = np.array(["hello", "world"])
words.dtype

dtype('<U5')

In [25]:
mixed_one = np.array(["hello", "world", 2020])
print(mixed_one)
print("shape: ", mixed_one.shape)
print("dtype: ", mixed_one.dtype)
print("type:", type(mixed_one))

['hello' 'world' '2020']
shape:  (3,)
dtype:  <U5
type: <class 'numpy.ndarray'>


#### when integer and floats values are mixed, NumPy upcast the data type. In this case as float64.
this is to avoid losing precision during numerical computations.

In [27]:
x = np.array([1,2,4.5,6.7])

In [28]:
print(x)
print("type:",type(x))
print("dtype:", x.dtype)
print("shape:", x.shape)
print("size:", x.size)

[1.  2.  4.5 6.7]
type: <class 'numpy.ndarray'>
dtype: float64
shape: (4,)
size: 4


#### if we want specific data type, we can specifiy it

In [29]:
x = np.array([1,2,3.7, 8.1], dtype=np.int64)

In [30]:
print(x)
print("type:", type(x))
print("dtype:", x.dtype)

[1 2 3 8]
type: <class 'numpy.ndarray'>
dtype: int64


# Saving NumPy array as .npy file
this allow to save the array as file, and load later for usage

In [31]:
y = np.array([1,2,3,4,5])
np.save('my_sample_array', y)

In [33]:
new_array = np.load('my_sample_array.npy')

In [34]:
print(new_array)

[1 2 3 4 5]


#### Exercises

In [47]:
import string
letters =  list(string.ascii_lowercase)[:10]

letter_array = np.array(letters)

print("letter array: ", letters)
print("type: ", type(letter_array))
print("dtype: ", letter_array.dtype)
print("shape: ", letter_array.shape)
print("size: ", letter_array.size)

letter array:  ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
type:  <class 'numpy.ndarray'>
dtype:  <U1
shape:  (10,)
size:  10


------------------------------------
## Using Built-in Functions to Create ndarrays

- zeros(shape)
- ones(shape)
- full(shape, constant value) 

In [52]:
x = np.zeros((5,4))
print(x)
print("dtype: ", x.dtype)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
dtype:  float64


In [55]:
x = np.ones((3,5), dtype=int)
print(x)
print("dtype: ", x.dtype)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
dtype:  int32


In [54]:
x = np.full((5,4), 5)
print(x)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


----------------------------

## Identity Matrix
An Identity matrix is a square matrix that has only 1s in its main diagonal and zeros everywhere else. 

there will be 1 value filled diagionally
- eye
- diag

In [56]:
x = np.eye(5)
print(x)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [58]:
x = np.diag([10,20,30,40])
print(x)

[[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 40]]


### using arange
- arange(start,stop,step)
- arange use integer value as step
- stop is exclusive

In [61]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [62]:
x = np.arange(1,21, 3)
print(x)

[ 1  4  7 10 13 16 19]


### using linspace
- linspace(start,stop,N)
- if we need to use float number as step, this is better choice
- start and stop are inclusive

In [64]:
x = np.linspace(0, 25, 10)
print(x)

[ 0.          2.77777778  5.55555556  8.33333333 11.11111111 13.88888889
 16.66666667 19.44444444 22.22222222 25.        ]


if we need to exclude the end number, we can use endpoint keyword to specify it

In [65]:
x = np.linspace(0, 25, 10, endpoint=False)
print(x)

[ 0.   2.5  5.   7.5 10.  12.5 15.  17.5 20.  22.5]


### using reshape
- reshape() helps to reshape the array
- RESHAPED ARRAY and ORIGINAL ARRAY needs to have same size of data. (example: 10 elements to 10 elments array only)

In [69]:
y = np.arange(20)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [73]:
x = np.reshape(y, (10,2))
print(x)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


In [74]:
# this will lead to error because the reshaped one doesn't have same elements of original one
z = np.reshape(y, (5,5))

ValueError: cannot reshape array of size 20 into shape (5,5)

#### using np methods by stacking

In [79]:
# using np method by stacking
x = np.arange(20).reshape((4,5))
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [80]:
x = np.linspace(1,25, 10).reshape((2,5))
print(x)

[[ 1.          3.66666667  6.33333333  9.         11.66666667]
 [14.33333333 17.         19.66666667 22.33333333 25.        ]]


-------------

### using Random
- random(shape)  : return random values between 0 and 1
- randint(start, stop, shape)
- normal(mean, standard deviation, size=shape)

In [81]:
X = np.random.random((2,3))
print(X)

[[0.22963809 0.54045383 0.67414111]
 [0.91734695 0.31318057 0.61133388]]


In [84]:
X = np.random.randint(1, 10, (2,3))
print(X)

[[6 9 4]
 [6 8 6]]


In [89]:
# We create a 1000 x 1000 ndarray of random floats drawn from normal (Gaussian) distribution
# with a mean of zero and a standard deviation of 0.1.

X = np.random.normal(0, 0.1, size=(1000, 1000))
print(X)

[[-0.01352094  0.04472152  0.06954855 ... -0.18208439  0.07611071
   0.15373464]
 [ 0.00523997  0.01955531  0.10339136 ...  0.25074709 -0.02989314
  -0.0591647 ]
 [ 0.1730195   0.09431604  0.06066716 ...  0.0593284  -0.09067788
   0.17501465]
 ...
 [-0.05232208 -0.06507077  0.01674555 ...  0.15150225  0.0013833
  -0.04937502]
 [-0.00694143  0.03661268 -0.20882724 ... -0.0743347   0.09439472
   0.04698592]
 [ 0.04144826  0.04557936  0.18440383 ...  0.06673141  0.04763279
  -0.01833472]]


In [91]:
# the average of the random numbers in the ndarray is close to zero, both the maximum and minimum values in X are symmetric about zero (the average), 
#and we have about the same amount of positive and negative numbers.

print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)
print('The elements in X have a mean of:', X.mean())
print('The maximum value in X is:', X.max())
print('The minimum value in X is:', X.min())
print('X has', (X < 0).sum(), 'negative numbers')
print('X has', (X > 0).sum(), 'positive numbers')

X has dimensions: (1000, 1000)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: float64
The elements in X have a mean of: -6.431934559489815e-05
The maximum value in X is: 0.5089841669801196
The minimum value in X is: -0.4643273840538273
X has 500226 negative numbers
X has 499774 positive numbers


#### Exercise

In [98]:
import numpy as np

# Using the Built-in functions you learned about in the
# previous lesson, create a 4 x 4 ndarray that only
# contains consecutive even numbers from 2 to 32 (inclusive)

X = np.arange(2, 33,2).reshape((4,4))
print(X)
print("type: ", type(X))

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]
type:  <class 'numpy.ndarray'>


----------------------

# Accessing, Deleting, and Inserting Elements Into ndarrays

In [99]:
x = np.array([1,2,3,4,5])
print(x)

[1 2 3 4 5]


In [102]:
# using positive index
print("1st element: ", x[0])
print("3rd element: ", x[2])
print("5th element: ", x[4])

1st element:  1
3rd element:  3
5th element:  5


In [103]:
#using negative index
print("1st element: ", x[-5])
print("3rd element: ", x[-3])
print("5th element: ", x[-1])

1st element:  1
3rd element:  3
5th element:  5


In [104]:
X = np.arange(1, 10).reshape((3,3))
print(X)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [105]:
print("element at (0,0): ", X[0,0])
print("element at (0,1): ", X[0,1])
print("element at (2,2): ", X[2,2])

element at (0,0):  1
element at (0,1):  2
element at (2,2):  9


In [106]:
X[0,0] = 20
print(X)

[[20  2  3]
 [ 4  5  6]
 [ 7  8  9]]


#### delete element from one dimensional array
- np.delete(array, position index list)

In [107]:
X = np.array([1,2,3,4,5])
print(X)

[1 2 3 4 5]


In [108]:
Y = np.delete(X, [0,3])
print(Y)

[2 3 5]


#### delete elements/ rows/ columns from multi dimensional array
- np.delete(array, row/column number, axis=0/1)
- axis 0: row
- axis 1: column

In [109]:
X = np.arange(1,10).reshape((3,3))
print(X)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [111]:
Y = np.delete(X, 0, axis=0)
print(Y)

[[4 5 6]
 [7 8 9]]


In [113]:
Z = np.delete(X, [0, 2], axis=1)
print(Z)

[[2]
 [5]
 [8]]


#### appending elements into one dimensional array
- np.append(array, elements list)

In [114]:
x = np.array([1,2,3,4,5])
print(x)

[1 2 3 4 5]


In [115]:
x = np.append(x, 6)
print(x)

[1 2 3 4 5 6]


In [116]:
x = np.append(x, [7,8,9,10])
print(x)

[ 1  2  3  4  5  6  7  8  9 10]


#### append elements into multi dimensional array
*** IMPORTANT : the items that you want to add needs to be in CORRECT shape ***
- np.append(array, elements list array, axis = 0/1)
- axis 0: row
- axis 1: column

In [117]:
X = np.arange(1,11).reshape(5,2)
print(X)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [120]:
X = np.append(X, [[11,12]], axis=0)
print(X)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [123]:
X = np.append(X, [[100], [200], [300], [400], [500], [600]], axis=1)
print(X)

[[  1   2 100]
 [  3   4 200]
 [  5   6 300]
 [  7   8 400]
 [  9  10 500]
 [ 11  12 600]]


#### Inserting elements into array
- np.insert(array, position, array list)

In [124]:
x = np.array([1,2,3,4,5])
print(x)

[1 2 3 4 5]


In [125]:
x = np.insert(x, 2, [600, 700])
print(x)

[  1   2 600 700   3   4   5]


#### inserting elements into multi dimensional array
- np.insert(array, position, arraylist, axis=0/1)

In [129]:
x = np.arange(1,10).reshape(3,3)
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [130]:
x= np.insert(x, 2, [1000, 2000, 3000],axis=0)
print(x)

[[   1    2    3]
 [   4    5    6]
 [1000 2000 3000]
 [   7    8    9]]


In [131]:
x = np.insert(x, 1, 666, axis=1)
print(x)

[[   1  666    2    3]
 [   4  666    5    6]
 [1000  666 2000 3000]
 [   7  666    8    9]]


## Stacking nd arrays
- np.vstack() : vertically
- np.hstack(): horizontally

In [136]:
x = np.array([1,2])
print(x)

[1 2]


In [137]:
y = np.array([[3,4], [5,6]])
print(y)

[[3 4]
 [5 6]]


In [140]:
z = np.vstack((x,y))
print(z)

[[1 2]
 [3 4]
 [5 6]]


In [141]:
A = np.hstack((z, [[100],[200],[300]]))
print(A)

[[  1   2 100]
 [  3   4 200]
 [  5   6 300]]
