In [2]:
import numpy as np

# 1.Data Types & Attributes

## A) NumPy Array

In [41]:
# main data type is ndarray
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [5]:
type(a1)

numpy.ndarray

In [18]:
a1.shape

(3,)

In [6]:
a2 = np.array([[1, 2.1, 3.2],
              [4.1, 5.2, 6.3]])

In [7]:
a2

array([[1. , 2.1, 3.2],
       [4.1, 5.2, 6.3]])

In [9]:
a2.shape

(2, 3)

In [16]:
a3 = np.array([
    [[1,2,3],[4,5,6],[1.1,1.2,1.3]],
    [[7,8,9],[10,11,12],[2.2,2.3,2.4]]
])
a3

array([[[ 1. ,  2. ,  3. ],
        [ 4. ,  5. ,  6. ],
        [ 1.1,  1.2,  1.3]],

       [[ 7. ,  8. ,  9. ],
        [10. , 11. , 12. ],
        [ 2.2,  2.3,  2.4]]])

In [17]:
a3.shape

(2, 3, 3)

In [19]:
a1.shape

(3,)

In [20]:
a2.shape

(2, 3)

In [22]:
# checking number of dimensions
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [23]:
# checking data type
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('float64'))

In [24]:
# checking size
a1.size, a2.size, a3.size

(3, 6, 18)

In [26]:
# checking type
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

## creating data frame from ndarray

In [27]:
import pandas as pd

In [32]:
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.1  3.2
1  4.1  5.2  6.3

In [37]:
arr = np.array([[1,2,3],[4,5,6]], 
                dtype=np.float32)
print(arr)
print(repr(arr))

[[1. 2. 3.]
 [4. 5. 6.]]
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)


## np.array upcasting

In [40]:
# np.array upcasting
arr = np.array([1,2.0,3])
print(repr(arr))
print(arr.dtype)

array([1., 2., 3.])
float64


## B) Copying

In [42]:
a = np.array([0, 1])
b = np.array([9, 8])
c = a
print('Array a: {}'.format(repr(a)))
c[0] = 5
print('Array a: {}'.format(repr(a)))

d = b.copy()
d[0] = 6
print('Array b: {}'.format(repr(b)))

Array a: array([0, 1])
Array a: array([5, 1])
Array b: array([9, 8])


## C) Casting

In [43]:
arr = np.array([0, 1, 2])
print(arr.dtype)
arr = arr.astype(np.float32)
print(arr.dtype)

int32
float32


## D) NaN

In [45]:
#NaN as place holder
#NaN cannot take integer

arr = np.array([np.nan, 1, 2])
print(repr(arr))

arr = np.array([np.nan, 'abc'])
print(repr(arr))

# Will result in a ValueError
np.array([np.nan, 1, 2], dtype=np.int32)

array([nan,  1.,  2.])
array(['nan', 'abc'], dtype='<U32')


ValueError: cannot convert float NaN to integer

## E) Infinity

In [47]:
# infinity can be postive or negative
# infinity cannot take integer type

print(np.inf > 1000000)

arr = np.array([np.inf, 5])
print(repr(arr))

arr = np.array([-np.inf, 1])
print(repr(arr))

# Will result in an OverflowError
np.array([np.inf, 3], dtype=np.int32)

True
array([inf,  5.])
array([-inf,   1.])


OverflowError: cannot convert float infinity to integer

## Exercise

In [51]:
# Set arr equal to np.array applied to the specified list.

arr = np.array([np.nan, 2,3,4,5])

In [52]:
type(arr)

numpy.ndarray

In [53]:
print(repr(arr))

array([nan,  2.,  3.,  4.,  5.])


In [54]:
#copy and change element of first array

arr2 = arr.copy()
arr2[0] = 10
print(arr2)
print(arr)

[10.  2.  3.  4.  5.]
[nan  2.  3.  4.  5.]


In [55]:
# type cast the array element
float_arr = np.array([1, 5.4, 3])
float_arr2 = arr2.astype(np.float32)

print(repr(float_arr))
print(repr(float_arr2))

array([1. , 5.4, 3. ])
array([10.,  2.,  3.,  4.,  5.], dtype=float32)


In [57]:
# multi dimensional array
matrix = np.array([[1,2,3],[4,5,6]], dtype=np.float32)

print(repr(matrix))
print(matrix)

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)
[[1. 2. 3.]
 [4. 5. 6.]]


# 2. Creating NumPy Arrays

In [3]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [5]:
ones = np.ones((2,3), dtype=float)

In [6]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [7]:
# usually ones and zeros are used for placeholder

In [8]:
zeros = np.zeros((3,2,3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [9]:
range_array = np.arange(0, 20, 2)
range_array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [10]:
# random 
random_array = np.random.randint(0, 20, size=(2,3))
random_array

array([[ 5, 16, 11],
       [ 6, 19,  9]])

In [11]:
random_array.size

6

In [12]:
random_array.shape

(2, 3)

In [13]:
random_array2 = np.random.random(size=(2,3,5))
random_array2

array([[[0.10598265, 0.00887499, 0.33309558, 0.08237521, 0.94716701],
        [0.15363234, 0.4169516 , 0.99812764, 0.24721219, 0.31958996],
        [0.21800861, 0.26131273, 0.22414384, 0.18166393, 0.41482586]],

       [[0.62519736, 0.05289272, 0.92472623, 0.55824327, 0.77453038],
        [0.99060319, 0.24415519, 0.7930045 , 0.97185267, 0.59803359],
        [0.8730036 , 0.75025246, 0.05216835, 0.78240348, 0.86210281]]])

In [14]:
random_array2.shape

(2, 3, 5)

In [15]:
random_array2.size

30

In [18]:
random_array3 = np.random.rand(2,3)
random_array3

array([[0.56462742, 0.18377192, 0.36245903],
       [0.61582447, 0.36808571, 0.40584363]])