In [1]:
import numpy as np
x = np.array([1, 2, 3, 4, 5])

## numpy array shape, size, type, dtype

In [2]:
type(x)

numpy.ndarray

In [5]:
x.dtype

dtype('int32')

## 1 dimensional array is rank 1
## 2 dimensionals array is rank 2, etc

In [6]:
x.shape

(5,)

In [8]:
Y = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(Y)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [9]:
Y.shape

(4, 3)

In [10]:
Y.size

12

In [11]:
Y.dtype

dtype('int32')

In [12]:
x = np.array([1, 2, 'Hello'])

In [13]:
x.dtype

dtype('<U11')

In [14]:
x.shape

(3,)

In [16]:
z = np.array([1.2, 3.4, 5.6])

In [17]:
print(z.dtype)
print(z.shape)
print(type(z))

float64
(3,)
<class 'numpy.ndarray'>


In [18]:
z

array([1.2, 3.4, 5.6])

In [19]:
z = np.array([1.2, 3.4, 5.6], dtype=np.int64)

In [20]:
print(z.dtype)
print(z.shape)
print(type(z))

int64
(3,)
<class 'numpy.ndarray'>


In [21]:
print(z)

[1 3 5]


## saving and loading numpy array

In [22]:
np.save('my_array', z)

In [24]:
A = np.load('my_array.npy')

In [25]:
A

array([1, 3, 5], dtype=int64)

## Exercise

Create a numpy array of strings containing letters 'a' through 'j' (inclusive) of the alphabet. Then, use numpy array attributes to print the following information about this array:

- dtype of array
- shape of array
- size of array

In [29]:
import string
# create numpy array of letters a-j
letter_array = np.array([x for x in string.ascii_lowercase]) 
print("Letter Array: ", letter_array)

Letter Array:  ['a' 'b' 'c' 'd' 'e' 'f' 'g' 'h' 'i' 'j' 'k' 'l' 'm' 'n' 'o' 'p' 'q' 'r'
 's' 't' 'u' 'v' 'w' 'x' 'y' 'z']


In [33]:
#type of the array
print('Type:', type(letter_array))

# get dtype of array
print("Dtype:", letter_array.dtype)

# get shape of array
print("Shape:", letter_array.shape)

# get size of array
print("Size:", letter_array.size)

Type: <class 'numpy.ndarray'>
Dtype: <U1
Shape: (26,)
Size: 26


------------

## creating ndarray using builtin function (zeros, ones, full, eye, diag)

In [35]:
# default dtype is float
zero_list = np.zeros((3,4))
print(zero_list)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [36]:
zero_list = np.zeros((3,4), dtype= int)
print(zero_list)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [37]:
one_list = np.ones((4,5), dtype = int)

In [38]:
print(one_list)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [40]:
# full function with default contant value
five_array = np.full((4,3), 5)
print(five_array)

[[5 5 5]
 [5 5 5]
 [5 5 5]
 [5 5 5]]


## Square Matrix

In [41]:
# eye
eye_array = np.eye(5)
print(eye_array)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [42]:
#diag
diag_array = np.diag([10,20,30,40])
print(diag_array)

[[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 40]]


## arange

In [43]:
#arange
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [45]:
x = np.arange(4, 10)
print(x)

[4 5 6 7 8 9]


In [46]:
x = np.arange(1, 11, 2)
print(x)

[1 3 5 7 9]


## linspace

In [47]:
x = np.linspace(0, 25, 10)
print(x)

[ 0.          2.77777778  5.55555556  8.33333333 11.11111111 13.88888889
 16.66666667 19.44444444 22.22222222 25.        ]


In [48]:
x = np.linspace(0, 25, 10, endpoint = False)
print(x)

[ 0.   2.5  5.   7.5 10.  12.5 15.  17.5 20.  22.5]


## reshape

In [50]:
x = np.arange(20)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [53]:
x = np.reshape(x, (4,5))
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [55]:
x = np.reshape(x, (10,2))
print(x)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


In [56]:
x = np.linspace(0, 50, 10, endpoint=False).reshape(5,2)
print(x)

[[ 0.  5.]
 [10. 15.]
 [20. 25.]
 [30. 35.]
 [40. 45.]]


## Random function

In [57]:
x = np.random.random((3,3))
print(x)

[[0.12665544 0.64329902 0.34886248]
 [0.06883336 0.63881645 0.57464502]
 [0.55529732 0.67653572 0.17619341]]


In [59]:
#start, stop, shape
x = np.random.randint(4, 15, (3,3))
print(x)

[[ 7  8 14]
 [ 5 14  9]
 [ 6 10 14]]


In [61]:
#mean : 0, std = 0.1
x = np.random.normal(0, 0.1, size = (1000, 100))
print(x)

[[ 0.23317026  0.03936691 -0.02464965 ...  0.07656566  0.17696859
  -0.24096699]
 [-0.13443464  0.18308137 -0.18747256 ...  0.1417932  -0.16199216
  -0.01007245]
 [-0.02567907 -0.16515877 -0.05418558 ...  0.03419662 -0.05586077
   0.08852899]
 ...
 [-0.00106234  0.10934859 -0.02151826 ... -0.07183639  0.02146154
   0.05822197]
 [ 0.00387328  0.04208244  0.12040691 ...  0.04115382  0.21460508
  -0.03841731]
 [-0.0288246   0.10100472  0.2645198  ... -0.01714568 -0.08511502
  -0.04343533]]


### Exercise

In [66]:
import numpy as np

# Using the Built-in functions you learned about in the # previous lesson, create a 4 x 4 ndarray that only
# contains consecutive even numbers from 2 to 32 (inclusive)

X = np.arange(2,33,2).reshape(4,4)
print(X)

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]


In [70]:
#Try creating the same array using the np.linspace() function.
X = np.linspace(0,32,16).reshape(4,4)
print(X)

[[ 0.          2.13333333  4.26666667  6.4       ]
 [ 8.53333333 10.66666667 12.8        14.93333333]
 [17.06666667 19.2        21.33333333 23.46666667]
 [25.6        27.73333333 29.86666667 32.        ]]


## Accessing, Deleting, and Inserting Elements Into ndarrays