# NumPy

- NumPy is very fast as this speed comes from the nature of NumPy arrays being memory-efficient and from optimized algorithms used by NumPy for doing arithmetic, statistical, and linear algebra operations.
- it has multidimensional array data structures that can represent vectors and matrices.
- NumPy has a large number of optimized built-in mathematical functions
- NumPy holds same data type in its arrays , regardelss of string, number, etc


At the core of NumPy is the ndarray, where nd stands for n-dimensional. An ndarray is a multidimensional array of elements all of the same type. In other words, an ndarray is a grid that can take on many shapes and can hold either numbers or strings.


In [3]:
import time
import numpy as np

In [5]:
x = np.random.random(100000000)

In [6]:
start = time.time()
average = sum(x) / len(x)
print(f"time to compute {time.time()-start}")

time to compute 21.606374502182007


In [7]:
#using numpy
start = time.time()
average = np.mean(x)
print(f"time to compute {time.time()-start}")

time to compute 0.13408756256103516


## Creating and Saving NumPy

- rank 1 array : one dimensional array
- rank 2 array: two dimensional array
- rank n array: n dimensional array

In [8]:
import numpy as np
x = np.array([1,2,3,4,5])

In [10]:
print(x)
print(type(x))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [13]:
x.dtype

dtype('int32')

In [14]:
x.shape

(5,)

In [21]:
x.size

5

In [17]:
Y = np.array([[1,2,3,4,5], [6,7,8,9,10]])

In [18]:
Y.dtype

dtype('int32')

In [19]:
Y.shape

(2, 5)

In [20]:
Y.size

10

--------------
#### NumPy holds elements as same data type in its array

In [22]:
words = np.array(["hello", "world"])
words.dtype

dtype('<U5')

In [25]:
mixed_one = np.array(["hello", "world", 2020])
print(mixed_one)
print("shape: ", mixed_one.shape)
print("dtype: ", mixed_one.dtype)
print("type:", type(mixed_one))

['hello' 'world' '2020']
shape:  (3,)
dtype:  <U5
type: <class 'numpy.ndarray'>


#### when integer and floats values are mixed, NumPy upcast the data type. In this case as float64.
this is to avoid losing precision during numerical computations.

In [27]:
x = np.array([1,2,4.5,6.7])

In [28]:
print(x)
print("type:",type(x))
print("dtype:", x.dtype)
print("shape:", x.shape)
print("size:", x.size)

[1.  2.  4.5 6.7]
type: <class 'numpy.ndarray'>
dtype: float64
shape: (4,)
size: 4


#### if we want specific data type, we can specifiy it

In [29]:
x = np.array([1,2,3.7, 8.1], dtype=np.int64)

In [30]:
print(x)
print("type:", type(x))
print("dtype:", x.dtype)

[1 2 3 8]
type: <class 'numpy.ndarray'>
dtype: int64


# Saving NumPy array as .npy file
this allow to save the array as file, and load later for usage

In [31]:
y = np.array([1,2,3,4,5])
np.save('my_sample_array', y)

In [33]:
new_array = np.load('my_sample_array.npy')

In [34]:
print(new_array)

[1 2 3 4 5]


## Creating and Saving NumPy (Exercises)

In [47]:
import string
letters =  list(string.ascii_lowercase)[:10]

letter_array = np.array(letters)

print("letter array: ", letters)
print("type: ", type(letter_array))
print("dtype: ", letter_array.dtype)
print("shape: ", letter_array.shape)
print("size: ", letter_array.size)

letter array:  ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
type:  <class 'numpy.ndarray'>
dtype:  <U1
shape:  (10,)
size:  10


------------------------------------
## Using Built-in Functions to Create ndarrays

- zeros(shape)
- ones(shape)
- full(shape, constant value) 

In [52]:
x = np.zeros((5,4))
print(x)
print("dtype: ", x.dtype)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
dtype:  float64


In [55]:
x = np.ones((3,5), dtype=int)
print(x)
print("dtype: ", x.dtype)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
dtype:  int32


In [54]:
x = np.full((5,4), 5)
print(x)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


----------------------------

## Identity Matrix
An Identity matrix is a square matrix that has only 1s in its main diagonal and zeros everywhere else. 

there will be 1 value filled diagionally
- eye
- diag

In [56]:
x = np.eye(5)
print(x)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [58]:
x = np.diag([10,20,30,40])
print(x)

[[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 40]]


### using arange
- arange(start,stop,step)
- arange use integer value as step
- stop is exclusive

In [61]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [62]:
x = np.arange(1,21, 3)
print(x)

[ 1  4  7 10 13 16 19]


### using linspace
- linspace(start,stop,N)
- if we need to use float number as step, this is better choice
- start and stop are inclusive

In [64]:
x = np.linspace(0, 25, 10)
print(x)

[ 0.          2.77777778  5.55555556  8.33333333 11.11111111 13.88888889
 16.66666667 19.44444444 22.22222222 25.        ]


if we need to exclude the end number, we can use endpoint keyword to specify it

In [65]:
x = np.linspace(0, 25, 10, endpoint=False)
print(x)

[ 0.   2.5  5.   7.5 10.  12.5 15.  17.5 20.  22.5]


### using reshape
- reshape() helps to reshape the array
- RESHAPED ARRAY and ORIGINAL ARRAY needs to have same size of data. (example: 10 elements to 10 elments array only)

In [69]:
y = np.arange(20)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [73]:
x = np.reshape(y, (10,2))
print(x)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


In [74]:
# this will lead to error because the reshaped one doesn't have same elements of original one
z = np.reshape(y, (5,5))

ValueError: cannot reshape array of size 20 into shape (5,5)

#### using np methods by stacking

In [79]:
# using np method by stacking
x = np.arange(20).reshape((4,5))
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [80]:
x = np.linspace(1,25, 10).reshape((2,5))
print(x)

[[ 1.          3.66666667  6.33333333  9.         11.66666667]
 [14.33333333 17.         19.66666667 22.33333333 25.        ]]


-------------

### using Random
- random(shape)  : return random values between 0 and 1
- randint(start, stop, shape)
- normal(mean, standard deviation, size=shape)

In [81]:
X = np.random.random((2,3))
print(X)

[[0.22963809 0.54045383 0.67414111]
 [0.91734695 0.31318057 0.61133388]]


In [84]:
X = np.random.randint(1, 10, (2,3))
print(X)

[[6 9 4]
 [6 8 6]]


In [89]:
# We create a 1000 x 1000 ndarray of random floats drawn from normal (Gaussian) distribution
# with a mean of zero and a standard deviation of 0.1.

X = np.random.normal(0, 0.1, size=(1000, 1000))
print(X)

[[-0.01352094  0.04472152  0.06954855 ... -0.18208439  0.07611071
   0.15373464]
 [ 0.00523997  0.01955531  0.10339136 ...  0.25074709 -0.02989314
  -0.0591647 ]
 [ 0.1730195   0.09431604  0.06066716 ...  0.0593284  -0.09067788
   0.17501465]
 ...
 [-0.05232208 -0.06507077  0.01674555 ...  0.15150225  0.0013833
  -0.04937502]
 [-0.00694143  0.03661268 -0.20882724 ... -0.0743347   0.09439472
   0.04698592]
 [ 0.04144826  0.04557936  0.18440383 ...  0.06673141  0.04763279
  -0.01833472]]


In [91]:
# the average of the random numbers in the ndarray is close to zero, both the maximum and minimum values in X are symmetric about zero (the average), 
#and we have about the same amount of positive and negative numbers.

print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)
print('The elements in X have a mean of:', X.mean())
print('The maximum value in X is:', X.max())
print('The minimum value in X is:', X.min())
print('X has', (X < 0).sum(), 'negative numbers')
print('X has', (X > 0).sum(), 'positive numbers')

X has dimensions: (1000, 1000)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: float64
The elements in X have a mean of: -6.431934559489815e-05
The maximum value in X is: 0.5089841669801196
The minimum value in X is: -0.4643273840538273
X has 500226 negative numbers
X has 499774 positive numbers


## Built-in Functions to Create ndarrays (Exercise)

In [98]:
import numpy as np

# Using the Built-in functions you learned about in the
# previous lesson, create a 4 x 4 ndarray that only
# contains consecutive even numbers from 2 to 32 (inclusive)

X = np.arange(2, 33,2).reshape((4,4))
print(X)
print("type: ", type(X))

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]
type:  <class 'numpy.ndarray'>


----------------------

# Accessing, Deleting, and Inserting Elements Into ndarrays

In [99]:
x = np.array([1,2,3,4,5])
print(x)

[1 2 3 4 5]


In [102]:
# using positive indices
print("1st element: ", x[0])
print("3rd element: ", x[2])
print("5th element: ", x[4])

1st element:  1
3rd element:  3
5th element:  5


In [103]:
#using negative indices
print("1st element: ", x[-5])
print("3rd element: ", x[-3])
print("5th element: ", x[-1])

1st element:  1
3rd element:  3
5th element:  5


In [104]:
X = np.arange(1, 10).reshape((3,3))
print(X)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Access elements in rank 2 ndarrays we need to provide 2 indices in the form [row, column]

In [105]:
print("element at (0,0): ", X[0,0])
print("element at (0,1): ", X[0,1])
print("element at (2,2): ", X[2,2])

element at (0,0):  1
element at (0,1):  2
element at (2,2):  9


In [106]:
X[0,0] = 20
print(X)

[[20  2  3]
 [ 4  5  6]
 [ 7  8  9]]


### Delete element from one dimensional array
- np.delete(ndarray, elements, axis)
 - For rank 1 ndarrays the axis keyword is not required. 

In [4]:
X = np.array([1,2,3,4,5])
print(X)

[1 2 3 4 5]


In [5]:
# deleting 1st and 4th element of  X array

Y = np.delete(X, [0,3])
print(Y)

[2 3 5]


### Delete elements/ rows/ columns from multi dimensional array
- np.delete(ndarray, elements, axis=0/1)
- axis 0: row
- axis 1: column
  - For rank 2 ndarrays, axis = 0 is used to select rows, and axis = 1 is used to select columns.
 

In [6]:
X = np.arange(1,10).reshape((3,3))
print(X)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
# delete the 1st row
Y = np.delete(X, 0, axis=0)
print(Y)

[[4 5 6]
 [7 8 9]]


In [8]:
# delete 1st and 3rd columns
Z = np.delete(X, [0, 2], axis=1)
print(Z)

[[2]
 [5]
 [8]]


### Appending elements into one dimensional array
- np.append(ndarray, elements, axis)

In [114]:
x = np.array([1,2,3,4,5])
print(x)

[1 2 3 4 5]


In [115]:
x = np.append(x, 6)
print(x)

[1 2 3 4 5 6]


In [116]:
x = np.append(x, [7,8,9,10])
print(x)

[ 1  2  3  4  5  6  7  8  9 10]


### Append elements into multi dimensional array
*** IMPORTANT : the items that you want to add needs to be in CORRECT shape ***
- np.append(array, elements list array, axis = 0/1)
- axis 0: row
- axis 1: column

In [9]:
X = np.arange(1,11).reshape(5,2)
print(X)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [10]:
# append a new row contaitning elements 11 and 12

X = np.append(X, [[11,12]], axis=0)
print(X)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [12]:
# append a new columns contaitning elements 100 to 600

X = np.append(X, [[100], [200], [300], [400], [500], [600]], axis=1)
print(X)

[[  1   2 100 100]
 [  3   4 200 200]
 [  5   6 300 300]
 [  7   8 400 400]
 [  9  10 500 500]
 [ 11  12 600 600]]


### Inserting elements into array
- np.insert(ndarray, position/index, elements array list)

In [14]:
x = np.array([1,2,3,4,5])
print(x)

[1 2 3 4 5]


In [15]:
#insert items 600 and 700 at the position of 2 (between 2 and 3)

x = np.insert(x, 2, [600, 700])
print(x)

[  1   2 600 700   3   4   5]


### Inserting elements into multi dimensional array
- np.insert(array, position, arraylist, axis=0/1)

In [23]:
x = np.arange(1,10).reshape(3,3)
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [24]:
x= np.insert(x, 2, [1000, 2000, 3000],axis=0)
print(x)

[[   1    2    3]
 [   4    5    6]
 [1000 2000 3000]
 [   7    8    9]]


In [25]:
# We insert a column full of 666s between the first and second column of y

x = np.insert(x, 1, 666, axis=1)
print(x)

[[   1  666    2    3]
 [   4  666    5    6]
 [1000  666 2000 3000]
 [   7  666    8    9]]


In [26]:
x = np.insert(x, 0, [85,86,87,88], axis = 1)
print(x)

[[  85    1  666    2    3]
 [  86    4  666    5    6]
 [  87 1000  666 2000 3000]
 [  88    7  666    8    9]]


## Stacking nd arrays
NumPy also allows us to stack ndarrays on top of each other, or to stack them side by side.

- np.vstack() : vertically
- np.hstack(): horizontally

In [27]:
x = np.array([1,2])
print(x)

[1 2]


In [28]:
y = np.array([[3,4], [5,6]])
print(y)

[[3 4]
 [5 6]]


In [30]:
#We stack x on top of Y

z = np.vstack((x,y))
print(z)

[[1 2]
 [3 4]
 [5 6]]


In [31]:
#We stack 100 to 300 on the right of z

A = np.hstack((z, [[100],[200],[300]]))
print(A)

[[  1   2 100]
 [  3   4 200]
 [  5   6 300]]


In [34]:
# We stack x on the right of Y. We need to reshape x in order to stack it on the right of Y.
B = np.hstack((Y, x.reshape(2,1)))
print(B)

[[4 5 6 1]
 [7 8 9 2]]


---------------------

# Slicing ndarrays
IMPORTANT: slicing only make the VIEW of original array. So if you want any changes, the original array will be changed too.

1. ndarray[start:end]
2. ndarray[start:]
3. ndarray[:end]

### for ndarray it will be ndarray[rows slicing, columns slicing]

In [35]:
import numpy as np

In [37]:
X = np.arange(1,21).reshape(4,5)
print(X)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [38]:
# row, columns
Z = X[1:4, 2:5]
print(Z)

[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


In [39]:
Z = X[1:, 2:]
print(Z)

[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


In [40]:
Z = X[0:3, 2:5]
print(Z)

[[ 3  4  5]
 [ 8  9 10]
 [13 14 15]]


In [44]:
# all elements from 3rd row
Z = X[2:3, :]
print(Z)

[[11 12 13 14 15]]


In [45]:
# all elements from 3rd row
Z = X[2:3, ]
print(Z)

[[11 12 13 14 15]]


In [46]:
# all elements from 3rd row
Z = X[2:3]
print(Z)

[[11 12 13 14 15]]


In [54]:
# all elements from 3rd row, in terms of rank 1 array
Z = X[2]
print(Z)

[11 12 13 14 15]


In [55]:
# all elements from 3rd column , in terms of rank 1 array
Z = X[:, 2]
print(Z)

[ 3  8 13 18]


In [56]:
# all elements from 3rd column , in terms of rank 2 array
Z = X[:, 2:3]
print(Z)

[[ 3]
 [ 8]
 [13]
 [18]]


### IMPORTANT: slicing only make the VIEW of original array. So if you want any changes, the original array will be changed too.

In [57]:
print(X)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [58]:
Z = X[1:, 2:]
print(Z)

[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


In [59]:
Z[2,2] = 555
print(Z)

[[  8   9  10]
 [ 13  14  15]
 [ 18  19 555]]


now the original array element got changed too.

In [61]:
print(X)

[[  1   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13  14  15]
 [ 16  17  18  19 555]]


## NumPy Copy function
- to avoid those changes in original array, we need to use NumPy copy function
- copy() create a whole new ndarray.

In [62]:
X = np.arange(1,21).reshape(4,5)
print(X)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [63]:
Z = X[1:, 2:].copy()
print(Z)

[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


In [64]:
Z[2,2] = 555
print(Z)

[[  8   9  10]
 [ 13  14  15]
 [ 18  19 555]]


now as we use copy(), the original array dosesn't get impacted !

In [66]:
print(X)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


### Using Indices ndarray

In [67]:
indices = np.array([1,3])
print(indices)

[1 3]


In [70]:
# getting rows using indices ndarray

Y = X[indices, :]
print(Y)

[[ 6  7  8  9 10]
 [16 17 18 19 20]]


In [71]:
# getting columns using indices ndarray
Z = X[:, indices]
print(Z)

[[ 2  4]
 [ 7  9]
 [12 14]
 [17 19]]


------------

### Diag() to select items
- np.diag(ndarray, k=N)
- select elements in diagionally

In [72]:
print(X)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [74]:
Z = np.diag(X)
print(Z)

[ 1  7 13 19]


### or set the diagional line and select items from above and below the MAIN DIAGIONAL LINE
- np.diag(ndarray, k=)
- k=positive values : above the line
- k=negative values: below the line

In [75]:
Z = np.diag(X, k=1)
print(Z)

[ 2  8 14 20]


In [76]:
Z = np.diag(X, k=2)
print(Z)

[ 3  9 15]


In [77]:
Z = np.diag(X, k=-1)
print(Z)

[ 6 12 18]


In [79]:
# if k=0 , then this will select the main diagional line
Z = np.diag(X, k=0)
print(Z)

[ 1  7 13 19]


--------------------

### Unique Values
- np.unique(ndarray)

In [80]:
X = np.array([[1,2,3], [4,5,6], [1,2,3]])
print(X)

[[1 2 3]
 [4 5 6]
 [1 2 3]]


In [81]:
Y = np.unique(X)
print(Y)

[1 2 3 4 5 6]


-------------------

# Boolean Indexing, Set Operations, and Sorting

## Boolean Indexing
- <, > , >=, <=
- &
- replacement =

In [108]:
X = np.arange(1,26).reshape(5,5)
print(X)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [109]:
# items > 10 only
print("The elements in X that are greater than 10:", X[X > 10])

The elements in X that are greater than 10: [11 12 13 14 15 16 17 18 19 20 21 22 23 24 25]


In [110]:
# items <= 7 only
print("The elements in X that less than or equal to 7:", X[X <=7])

The elements in X that less than or equal to 7: [1 2 3 4 5 6 7]


In [87]:
# replace items with -1, when they are less 7
X[X<=7] = -1
print(X)

[[-1 -1 -1 -1 -1]
 [-1 -1  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [111]:
# items >=20 & <=25
print("The elements in X that are between 20 and 25:", X[(X >= 20) & (X <=25)])

The elements in X that are between 20 and 25: [20 21 22 23 24 25]


---------

## Set Operations
- Intersection: np.intersect1d(ndarray, ndarray)
- Union: np.union1d(ndarray, ndarry)
- Difference : np.setdiff1d(ndarray, ndarray)

In [90]:
x = np.array([1,2,3,4,5])
y = np.array([6,7,2,8,4])

In [112]:
print("Intersection: ", np.intersect1d(x, y))
print("Union: ", np.union1d(x,y))
print("Difference (LEFT JOIN): ", np.setdiff1d(x, y))

Intersection:  [2 6 7]
Union:  [ 1  2  3  4  6  7  8 10]
Difference (LEFT JOIN):  [ 1  3 10]


------------

## Sorting
- np.sort(ndarray)
- ndarray.sort() as a function, will sort the original array

In [117]:
x = np.random.randint(1, 11, size=(10,))
print(x)

[1 5 6 3 6 8 5 7 1 4]


In [118]:
# np.sort doesn't change the original array, but return the sorted result

print("'Sorted x (out of place):'", np.sort(x))
print("Original X: ", x)

'Sorted x (out of place):' [1 1 3 4 5 5 6 6 7 8]
Original X:  [1 5 6 3 6 8 5 7 1 4]


In [120]:
# sorting only for unique values
# We sort x but only keep the unique elements in x
print(np.sort(np.unique(x)))

[1 3 4 5 6 7 8]


In [122]:
# sort using as a method
## We sort x and print the sorted array using sort as a method.
x.sort()

# When we sort in place the original array is changed to the sorted array. To see this we print x again
print('x after sorting:', x)

x after sorting: [1 1 3 4 5 5 6 6 7 8]


### sorting n rank ndarray
- np.sort(ndarray, axis=0/1)
- When sorting rank 2 ndarrays, we need to specify to the np.sort() function whether we are sorting by rows or columns. This is done by using the axis keyword. 

In [104]:
X = np.random.randint(1,11, size=(5,5))
print(X)

[[ 9  6  8 10  8]
 [ 4  2  6  6  7]
 [10  4  9  2  9]
 [ 5  5 10 10  5]
 [ 9  5  3  3  1]]


In [105]:
# sorting row values (vertically)
print(np.sort(X, axis=0))

[[ 4  2  3  2  1]
 [ 5  4  6  3  5]
 [ 9  5  8  6  7]
 [ 9  5  9 10  8]
 [10  6 10 10  9]]


In [106]:
# sorting columns values (horizontally)
print(np.sort(X, axis=1))

[[ 6  8  8  9 10]
 [ 2  4  6  6  7]
 [ 2  4  9  9 10]
 [ 5  5  5 10 10]
 [ 1  3  3  5  9]]


-------------

# Manipulating ndarrays (Exercises)

In [128]:
import numpy as np

# Create a 5 x 5 ndarray with consecutive integers from 1 to 25 (inclusive).
# Afterwards use Boolean indexing to pick out only the odd numbers in the array

# Create a 5 x 5 ndarray with consecutive integers from 1 to 25 (inclusive).
X = np.arange(1,26).reshape(5,5)
print("Original X")
print(X)

# Use Boolean indexing to pick out only the odd numbers in the array
Y = X[X%2!=0]
print()
print(Y)

Original X
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

[ 1  3  5  7  9 11 13 15 17 19 21 23 25]


----------------

# Arithmetic operations and Broadcasting

Broadcasting is the term used to describe how NumPy handles element-wise arithmetic operations with ndarrays of different shapes. For example, broadcasting is used implicitly when doing arithmetic operations between scalars and ndarrays.

## Arithmetic operations
- elements wise operations
- matrix operations

It is important to note that when performing element-wise operations, the shapes of the ndarrays being operated on, must have the same shape or be broadcastable. 

In [129]:
import numpy as np

In [130]:
x = np.arange(1,6)
y = np.arange(6,11)
print(x)
print(y)

[1 2 3 4 5]
[ 6  7  8  9 10]


In [135]:
z = x + y
print(z)
print(np.add(x,y))

[ 7  9 11 13 15]
[ 7  9 11 13 15]


In [136]:
z = x - y
print(z)
print(np.subtract(x,y ))

[-5 -5 -5 -5 -5]
[-5 -5 -5 -5 -5]


In [137]:
z = x/y
print(z)
print(np.divide(x,y))

[0.16666667 0.28571429 0.375      0.44444444 0.5       ]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [138]:
z = x * y
print(z)
print(np.multiply(x,y))

[ 6 14 24 36 50]
[ 6 14 24 36 50]


In [180]:
# We create two rank 2 ndarrays
X = np.array([1,2,3,4]).reshape(2,2)
Y = np.array([5.5,6.5,7.5,8.5]).reshape(2,2)

# We print X
print()
print('X = \n', X)

# We print Y
print()
print('Y = \n', Y)
print()

# We perform basic element-wise operations using arithmetic symbols and functions
print('X + Y = \n', X + Y)
print()
print('add(X,Y) = \n', np.add(X,Y))
print()
print('X - Y = \n', X - Y)
print()
print('subtract(X,Y) = \n', np.subtract(X,Y))
print()
print('X * Y = \n', X * Y)
print()
print('multiply(X,Y) = \n', np.multiply(X,Y))
print()
print('X / Y = \n', X / Y)
print()
print('divide(X,Y) = \n', np.divide(X,Y))


X = 
 [[1 2]
 [3 4]]

Y = 
 [[5.5 6.5]
 [7.5 8.5]]

X + Y = 
 [[ 6.5  8.5]
 [10.5 12.5]]

add(X,Y) = 
 [[ 6.5  8.5]
 [10.5 12.5]]

X - Y = 
 [[-4.5 -4.5]
 [-4.5 -4.5]]

subtract(X,Y) = 
 [[-4.5 -4.5]
 [-4.5 -4.5]]

X * Y = 
 [[ 5.5 13. ]
 [22.5 34. ]]

multiply(X,Y) = 
 [[ 5.5 13. ]
 [22.5 34. ]]

X / Y = 
 [[0.18181818 0.30769231]
 [0.4        0.47058824]]

divide(X,Y) = 
 [[0.18181818 0.30769231]
 [0.4        0.47058824]]


## Broadcasting
- both arrays need to be in same shape
- np.sqrt()
- np.exp()
- np.power()

Broadcasting is the term used to describe how NumPy handles element-wise arithmetic operations with ndarrays of different shapes. For example, broadcasting is used implicitly when doing arithmetic operations between scalars and ndarrays.


In [139]:
print(x + y)

[ 7  9 11 13 15]


In [140]:
z = np.sqrt(x)
print(z)

[1.         1.41421356 1.73205081 2.         2.23606798]


In [141]:
z = np.exp(x)
print(z)

[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [142]:
z = np.power(x,2)
print(z)

[ 1  4  9 16 25]


### Statistical Operations
- np.average(ndarray)
- ndarray.mean()
- ndarray.sum()
- np.median(ndarray)
- ndarray.min()
- ndarry.max()
- ndarray.std()

In [145]:
X = np.array([[1,2],[3,4]])
print(X)

[[1 2]
 [3 4]]


#### Mean / Average

In [149]:
average = np.average(X)
print("Average of all: ", average)

mean = X.mean()
print("Mean of All: ", mean)

Average of all:  2.5
Mean of All:  2.5


In [150]:
average_col = np.average(X, axis=1)
average_row = np.average(X, axis=0)
print("Average of Rows: ", average_row)
print("Average of Columns: ", average_col)

average_col = X.mean(axis=1)
average_row = X.mean(axis=0)
print("Average of Rows: ", average_row)
print("Average of Columns: ", average_col)

Average of Rows:  [2. 3.]
Average of Columns:  [1.5 3.5]
Average of Rows:  [2. 3.]
Average of Columns:  [1.5 3.5]


### Sum

In [152]:
total_sum = X.sum()
sum_col = X.sum(axis=1)
sum_row = X.sum(axis=0)

print(X)
print("Sum of All: ", total_sum)
print("Sum of Rows: ", sum_row)
print("Sum of Cols: ", sum_col)

[[1 2]
 [3 4]]
Sum of All:  10
Sum of Rows:  [4 6]
Sum of Cols:  [3 7]


### Standard Deviation

In [153]:
std_dev = X.std()
print("Standard Deviation: ", std_dev)

Standard Deviation:  1.118033988749895


### Min, Max, Median

In [157]:
##### min_val = X.min()
max_val = X.max()
median_val = np.median(X)

print("Min: ", min_val)
print("Max: ", max_val)
print("Median: ", median_val)

Min:  1
Max:  4
Median:  2.5


In [181]:
# We create a 2 x 2 ndarray
X = np.array([[1,2], [3,4]])

# We print x
print()
print('X = \n', X)
print()

print('Average of all elements in X:', X.mean())
print('Average of all elements in the columns of X:', X.mean(axis=0))
print('Average of all elements in the rows of X:', X.mean(axis=1))
print()
print('Sum of all elements in X:', X.sum())
print('Sum of all elements in the columns of X:', X.sum(axis=0))
print('Sum of all elements in the rows of X:', X.sum(axis=1))
print()
print('Standard Deviation of all elements in X:', X.std())
print('Standard Deviation of all elements in the columns of X:', X.std(axis=0))
print('Standard Deviation of all elements in the rows of X:', X.std(axis=1))
print()
print('Median of all elements in X:', np.median(X))
print('Median of all elements in the columns of X:', np.median(X,axis=0))
print('Median of all elements in the rows of X:', np.median(X,axis=1))
print()
print('Maximum value of all elements in X:', X.max())
print('Maximum value of all elements in the columns of X:', X.max(axis=0))
print('Maximum value of all elements in the rows of X:', X.max(axis=1))
print()
print('Minimum value of all elements in X:', X.min())
print('Minimum value of all elements in the columns of X:', X.min(axis=0))
print('Minimum value of all elements in the rows of X:', X.min(axis=1))


X = 
 [[1 2]
 [3 4]]

Average of all elements in X: 2.5
Average of all elements in the columns of X: [2. 3.]
Average of all elements in the rows of X: [1.5 3.5]

Sum of all elements in X: 10
Sum of all elements in the columns of X: [4 6]
Sum of all elements in the rows of X: [3 7]

Standard Deviation of all elements in X: 1.118033988749895
Standard Deviation of all elements in the columns of X: [1. 1.]
Standard Deviation of all elements in the rows of X: [0.5 0.5]

Median of all elements in X: 2.5
Median of all elements in the columns of X: [2. 3.]
Median of all elements in the rows of X: [1.5 3.5]

Maximum value of all elements in X: 4
Maximum value of all elements in the columns of X: [3 4]
Maximum value of all elements in the rows of X: [2 4]

Minimum value of all elements in X: 1
Minimum value of all elements in the columns of X: [1 2]
Minimum value of all elements in the rows of X: [1 3]


## Broadcast the array with constant value / or with another array
numpy make sure to do operations for each elements, so that the array can maintain the shape

NumPy is working behind the scenes to broadcast 3 along the ndarray so that they have the same shape. This allows us to add 3 to each element of X with just one line of code.

In [163]:
print(x)

[1 2 3 4 5]


NumPy can add single numbers to all the elements of an ndarray without the use of complicated loops.

In [164]:
z = x * 3
print(z)

[ 3  6  9 12 15]


In [165]:
z = x / 3
print(z)

[0.33333333 0.66666667 1.         1.33333333 1.66666667]


In [166]:
z = x + 3
print(z)

[4 5 6 7 8]


In [167]:
z = x -3 
print(z)

[-2 -1  0  1  2]


#### using another ndarray

In [174]:
x = np.array([[1,2,3],[4,5,6], [7,8,9]])
y = np.array([1,2,3])
print(x)
print()
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[1 2 3]


now when y is added to x, each element of y value is added to x 


In [175]:
z = x + y
print(z)

[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]


-----------------

In [176]:
y = y.reshape((3,1))
print(y)

[[1]
 [2]
 [3]]


In [178]:
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


NumPy is able to add 1 x 3 and 3 x 1 ndarrays to 3 x 3 ndarrays by broadcasting the smaller ndarrays along the big ndarray so that they have compatible shapes. In general, NumPy can do this provided that the smaller ndarray, such as the 1 x 3 ndarray in our example, can be expanded to the shape of the larger ndarray in such a way that the resulting broadcast is unambiguous.


In [177]:
z = x + y
print(z)

[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]


## Creating ndarrays with Broadcasting (Exercises)

In [187]:
import numpy as np

# Use Broadcasting to create a 4 x 4 ndarray that has its first
# column full of 1s, its second column full of 2s, its third
# column full of 3s, etc.. 

X = np.ones(shape=(4,4), dtype=int) * np.array([[1,2,3,4]])
print(X)

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]


In [189]:
import numpy as np

# Use Broadcasting to create a 4 x 4 ndarray that has its first
# column full of 1s, its second column full of 2s, its third
# column full of 3s, etc.. 

X = np.ones((4,4)) * np.arange(1,5)
print(X)

[[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]
